import { CircuitBlock, SchematicLayout, ScrCommand } from "../types/index.js";
import { REC_LIBRARY_NAME } from "../knowledge/eagle-libraries.js";

// ── Eagle SCR Script Generator ──
// Generates .scr files for Fusion 360 Electronics (Eagle).
//
// Command reference sourced from autodesk-coder MCP:
//   get_ecad("Schematic Editor Commands")
//
// Key commands used:
//   USE   — load a library so ADD can find parts
//   ADD   — place a deviceset from a library onto the schematic
//   NET   — draw a named net (electrical connection)
//   NAME  — rename components or nets
//   VALUE — assign a value to a component
//   LABEL — place a visible net name label
//   JUNCTION — place a net junction dot
//   MOVE  — reposition objects
//   ROTATE — rotate objects by 90°
//   GRID  — set the working grid
//   WINDOW — zoom/fit commands
//   EDIT  — switch sheets (.s1, .s2, etc.)

export class ScrBuilder {
  private commands: ScrCommand[] = [];

  // ── Setup ──

  useLibrary(libraryName: string = REC_LIBRARY_NAME): this {
    this.add(`USE '${libraryName}';`, "Load component library");
    return this;
  }

  setGrid(size: number, unit: "mil" | "mm" = "mil"): this {
    this.add(`GRID ${unit} ${size};`, "Set grid");
    return this;
  }

  setSheet(sheet: number = 1): this {
    this.add(`EDIT .s${sheet};`, `Switch to sheet ${sheet}`);
    return this;
  }

  setLayer(layer: string): this {
    this.add(`LAYER ${layer};`, `Switch to layer ${layer}`);
    return this;
  }

  // ── Component Placement ──
  // ADD command format per Eagle/Fusion Electronics:
  //   ADD 'DEVICESET_NAME[VARIANT]' REFDES ROTATION (X Y);
  //
  // The deviceset name is the part name from the REC library.
  // Examples:
  //   ADD '10K_0805' R1 R0 (500 1800);
  //   ADD 'ESP32-WROVER' A1 R0 (1000 1200);
  //   ADD '0.1UF_0603_5%_50V' C1 R0 (600 1800);
  //   ADD 'STM32F103C8T6-M' CR1 R0 (800 1000);  ← -M variant
  //   ADD '+3.3V' (500 2000);                      ← supply symbol, no refdes

  addComponent(
    devicesetName: string,
    refDes: string,
    x: number,
    y: number,
    rotation: number = 0,
    variant?: string
  ): this {
    const deviceName = variant ? `${devicesetName}${variant}` : devicesetName;
    const rotStr = `R${rotation}`;
    this.add(
      `ADD '${deviceName}' ${refDes} ${rotStr} (${x} ${y});`,
      `Place ${refDes} — ${devicesetName}`
    );
    return this;
  }

  addSupplySymbol(symbolName: string, x: number, y: number): this {
    this.add(`ADD '${symbolName}' (${x} ${y});`, `Supply: ${symbolName}`);
    return this;
  }

  setValue(refDes: string, value: string): this {
    this.add(`VALUE ${refDes} '${value}';`, `Set ${refDes} = ${value}`);
    return this;
  }

  nameComponent(refDes: string, newName: string): this {
    this.add(`NAME ${refDes} '${newName}';`, `Rename to ${newName}`);
    return this;
  }

  placeBlock(block: CircuitBlock, originX: number, originY: number, spacing: number = 200): this {
    this.addComment(`── ${block.name} ──`);
    block.components.forEach((comp, i) => {
      const row = Math.floor(i / 4);
      const col = i % 4;
      const x = originX + col * spacing;
      const y = originY - row * spacing;
      this.addComponent(
        comp.eagleDevice, // In our data this is now the REC deviceset name
        comp.refDes,
        x,
        y
      );
      if (comp.value) {
        this.setValue(comp.refDes, comp.value);
      }
    });
    return this;
  }

  // ── Net Drawing ──
  // NET command draws a named electrical connection.
  //   NET 'NET_NAME' (X1 Y1) (X2 Y2) ... ;
  // Nets with the same name are connected even across sheets.

  drawNet(netName: string, points: Array<{ x: number; y: number }>): this {
    if (points.length < 2) return this;
    const pointStr = points.map((p) => `(${p.x} ${p.y})`).join(" ");
    this.add(`NET '${netName}' ${pointStr};`, `Net: ${netName}`);
    return this;
  }

  addLabel(netName: string, x: number, y: number): this {
    this.add(`LABEL '${netName}' (${x} ${y});`, `Label: ${netName}`);
    return this;
  }

  addJunction(x: number, y: number): this {
    this.add(`JUNCTION (${x} ${y});`, "Junction");
    return this;
  }

  // ── Text and Annotations ──

  addText(text: string, x: number, y: number, size: number = 70): this {
    this.add(`TEXT '${text}' R0 (${x} ${y});`, `Text: ${text}`);
    return this;
  }

  addComment(comment: string): this {
    this.commands.push({ command: `# ${comment}` });
    return this;
  }

  // ── Full Layout ──

  generateFromLayout(layout: SchematicLayout): this {
    this.addComment("Generated by rec-circuit-design MCP");
    this.addComment(`Date: ${new Date().toISOString().split("T")[0]}`);
    this.addComment("Run in Fusion 360 Electronics: Automate > Script");
    this.addComment("");

    // Load the REC library first
    this.useLibrary();
    this.setGrid(100, "mil");
    this.setSheet(1);
    this.commands.push({ command: "" });

    layout.blocks.forEach((placed) => {
      this.placeBlock(placed.block, placed.originX, placed.originY);
      this.commands.push({ command: "" });
    });

    if (layout.globalNets.length > 0) {
      this.addComment("── Global Nets ──");
    }

    return this;
  }

  // ── Output ──

  private add(command: string, comment?: string): void {
    this.commands.push({ command, comment });
  }

  build(): string {
    const lines = this.commands.map((cmd) => {
      if (cmd.command.startsWith("#")) return cmd.command;
      if (cmd.command === "") return "";
      return cmd.comment ? `${cmd.command}  # ${cmd.comment}` : cmd.command;
    });

    return [
      "# Eagle SCR Script — Fusion 360 Electronics",
      "# Generated by rec-circuit-design MCP",
      `# Date: ${new Date().toISOString().split("T")[0]}`,
      `# Library: ${REC_LIBRARY_NAME}`,
      "#",
      "# Run: Fusion 360 > Electronics > Automate > Script",
      "# Or: command line > SCRIPT 'path/to/file.scr'",
      "",
      ...lines,
      "",
      "WINDOW FIT;  # Zoom to fit all components",
    ].join("\n");
  }

  reset(): this {
    this.commands = [];
    return this;
  }
}
