import { ComponentNote } from "../types/index.js";

// ── Notes about specific components ──
// Warnings, tips, EOL notices, quality issues, etc.

export const componentNotes: ComponentNote[] = [
  {
    id: "cn-001",
    partNumber: "AMS1117-3.3",
    note: "Reliable and cheap but quiescent current is 5mA — do not use for battery-powered designs. Use AP2112K-3.3 (Iq=55uA) or ME6211 (Iq=40uA) instead.",
    type: "tip",
    status: "approved",
    addedDate: "2026-02-28",
  },
  {
    id: "cn-002",
    partNumber: "CH340G",
    note: "Requires external 12MHz crystal. CH340C is crystal-less drop-in if you want to reduce BOM count. Both work but C version is easier for small boards.",
    type: "tip",
    status: "approved",
    addedDate: "2026-02-28",
  },

  // ── Carter-Hoffmann Slack Archive Notes ──

  {
    id: "cn-003",
    partNumber: "BTA12-600BWRG",
    note: "Supply-constrained since 2021. Verified drop-in replacements: BTA12-700BWRG and BTA12-800BWRG (same package, higher voltage rating). Requires UL file update when substituting. Derate to 5A max in production despite 12A datasheet rating.",
    type: "substitute",
    status: "approved",
    addedDate: "2026-02-28",
  },
  {
    id: "cn-004",
    partNumber: "T1235-600G-TR",
    note: "12A/600V TRIAC used in M-Series triac boards. Derate to 5A for production use. Heatsink required — used with heat-sinked bottom heater outputs on 15-output triac board. UL listed for Carter-Hoffmann applications.",
    type: "tip",
    status: "approved",
    addedDate: "2026-02-28",
  },
  {
    id: "cn-005",
    partNumber: "HC08",
    note: "WARNING: HC08 quad AND gate has slower propagation delay than HCS08. On M-Series display boards, this slower speed is actually REQUIRED for proper button detection on single-window displays daisy-chained downstream of dual-window masters. Do not blindly upgrade to HCS08 without full regression testing across all display configurations.",
    type: "warning",
    status: "approved",
    addedDate: "2026-02-28",
  },
  {
    id: "cn-006",
    partNumber: "HCS08",
    note: "Faster AND gate that fixes display flicker caused by cable capacitance on shift register lines. However, this speed change breaks button detection on downstream single-window displays (FGLF0626/0627) when chained after dual-window masters (FGLF0598/0599). Must stock both HC08 and HCS08 variants depending on display configuration.",
    type: "warning",
    status: "approved",
    addedDate: "2026-02-28",
  },
  {
    id: "cn-007",
    partNumber: "JST_S3B-PH-SM4-TB_LF_SN",
    note: "JST PH series used extensively in Carter-Hoffmann designs. DigiKey cable: 455-3143-ND, header: 455-1751-1-ND. Small, inexpensive, tight locking. Good for 4-wire comm+power connections as alternative to telco cables.",
    type: "tip",
    status: "approved",
    addedDate: "2026-02-28",
  },
  {
    id: "cn-008",
    partNumber: "RJ11-6P",
    note: "DO NOT USE for digital communication in new designs. Years of field failures on Carter-Hoffmann M-Series traced to 6-pin telco cable quality variations — crimping inconsistency, no shielding, no twisted pairs, variable capacitance. Use RJ45 CAT-5e instead. If forced to use RJ11, specify Assmann WSW A-MO-6-6-F50 plugs with documented crimping procedure.",
    type: "warning",
    status: "approved",
    addedDate: "2026-02-28",
  },

  // ── Devon-REC / Nidek Battery Pack Notes (from Slack archive 2019-2025) ──

  {
    id: "cn-009",
    partNumber: "BQ40Z60",
    note: "1MHz synchronous buck charger with integrated fuel gauge. Internal FET temperature can reach 66°C+ during charging. A marginal IC can cause FET overheating — check BQ IC temp before replacing FETs. SREC file contains chemistry, parameters, AND lifetime data. Correct programming order: firmware first, then chemistry.",
    type: "warning",
    status: "approved",
    addedDate: "2026-02-28",
  },
  {
    id: "cn-010",
    partNumber: "BQ40Z50",
    note: "All hardware revisions (base, R1, R2, R3, R4) are the same silicon die. Upgrade between revisions by flashing firmware only. R4 firmware file is v4.02build79. Place the .BQZ file in BQStudio config folder for R4 to appear as device option. TI app note SLUAAE2 confirms hardware compatibility. This opens up supply chain significantly — accept any revision.",
    type: "tip",
    status: "approved",
    addedDate: "2026-02-28",
  },
  {
    id: "cn-011",
    partNumber: "BQ294700",
    note: "WARNING: Floating cell sense inputs when IC is powered WILL trigger fuse blow output and latch active. Route power supply for this IC through the final cell connection switch so it only powers on after all cells are present. For existing boards: open all dip switches, solder B- through B3 first, close dip switches, THEN solder B4. Verify FUSE flag in BQStudio before enabling. BQ294711 is a drop-in with wider threshold options.",
    type: "warning",
    status: "approved",
    addedDate: "2026-02-28",
  },
  {
    id: "cn-012",
    partNumber: "BQ24610",
    note: "600kHz synchronous buck battery charger. Good efficiency (~100% at 46W through-put). TS pin controls charge enable — must drive to ~1.8V (50% of 3.3V VREF) or use 10KΩ to GND. TS can't be left floating — needs explicit biasing. Eval board has no snubber populated — add RC snubber (10Ω + 2200pF) to output FETs for EMI compliance. Input voltage must be > battery voltage for charging to start.",
    type: "tip",
    status: "approved",
    addedDate: "2026-02-28",
  },
  {
    id: "cn-013",
    partNumber: "BQ771605DPJR",
    note: "External overvoltage detector with 3.85V per-cell trip point. Used alongside BQ40Z50/BQ40Z60 in battery pack designs as hardware safety backup. Set software COV threshold below 3.85V (recommend 3750mV) to ensure software catches overvoltage before this hardware detector fires.",
    type: "tip",
    status: "approved",
    addedDate: "2026-02-28",
  },
  {
    id: "cn-014",
    partNumber: "INR18650MJ1",
    note: "Samsung 18650 Li-ion cell used in Nidek O2 concentrator battery packs. TI Chemistry ID 0x2059. Be careful: TI auto-analysis sometimes mis-identifies as Panasonic 18650 if current calibration is off. Available in TI GAUGECHEM software Chemistry Version 997+.",
    type: "tip",
    status: "approved",
    addedDate: "2026-02-28",
  },
  {
    id: "cn-015",
    partNumber: "EV2400",
    note: "TI evaluation interface board for BQStudio communication with BQ fuel gauge ICs. BQStudio runs on Windows only and is prone to random reboots from Windows updates during long learning cycles. Disable automatic updates on the test machine. Use version 1.3.101+ with Chemistry version 997+. Headless machines need network access for remote monitoring.",
    type: "tip",
    status: "approved",
    addedDate: "2026-02-28",
  },

  // ── Polyvance Plastic Welder Notes (from Slack archive 2019-2025) ──

  {
    id: "cn-016",
    partNumber: "4118L-07P",
    note: "Lin Engineering 4118L-07P bipolar stepper motor used for nitrogen flow control valve. 1.8°/step (200 steps/rev), 2000 steps for full valve range. Requires 300mA drive current. Must rewind-to-home on every power cycle — no absolute position feedback. Pair with MAC valve body for gas flow control. Hysteresis in valve means always approach setpoints from same direction.",
    type: "tip",
    status: "approved",
    addedDate: "2026-02-28",
  },
  {
    id: "cn-017",
    partNumber: "PTS0603",
    note: "Vishay PTS0603 platinum RTD thin-film sensor. Used for handle temperature measurement in plastic welder. Mount on small custom PCB (~8mm x 12mm) with JST PH connector for easy replacement. Better accuracy than NTC for temperature control loops. Use 4-wire measurement or Kelvin connection for precision; 2-wire acceptable for safety cutoff applications where ±2°C is sufficient.",
    type: "tip",
    status: "approved",
    addedDate: "2026-02-28",
  },
  {
    id: "cn-018",
    partNumber: "IRM-05-5",
    note: "Meanwell IRM-05-5 board-mount AC-DC module. 5V/1A output, 85-264VAC universal input, fully enclosed/potted. UL/CE certified. Smaller and cheaper than discrete transformer + regulator for low-power embedded systems. Pin-compatible IRM series covers 5V, 12V, 15V, 24V at 5-20W. Replaces traditional power supply approach in industrial controllers.",
    type: "tip",
    status: "approved",
    addedDate: "2026-02-28",
  },
  {
    id: "cn-019",
    partNumber: "BTA12-600BW",
    note: "Same TRIAC as BTA12-600BWRG but non-RoHS variant. UL listed under UL1557, file reference 81734, for Polyvance plastic welder applications. Used for heater element control with zero-crossing detection. Derate to 5A max (same rule as Carter-Hoffmann). Zero-crossing detection circuit must be routed away from shift register or other fast digital signals — capacitive coupling causes false triggering.",
    type: "warning",
    status: "approved",
    addedDate: "2026-02-28",
  },
  {
    id: "cn-020",
    partNumber: "RPi-Zero-W",
    note: "Raspberry Pi Zero W used as display controller in plastic welder (Bugatti variant). FCC ID: 2ABCB-RPI0W. 1024x600 IPS display via HDMI. BOM with display: ~$107 vs $49 for ESP32+7\" capacitive touch. Main risk: SD card corruption from power loss — expect ~5% annual failure rate without mitigation. Requires advance power-down circuit for reliable operation. Consider read-only rootfs with tmpfs overlays. Production touchscreen fallout ~10% (19/200 units).",
    type: "warning",
    status: "approved",
    addedDate: "2026-02-28",
  },
  {
    id: "cn-021",
    partNumber: "LD15-23B12R2",
    note: "Mornsun 12V/1.25A board-mount AC-DC module. Needed UL test report (not just UL certificate) for Polyvance welder safety certification. UL test reports are harder to obtain than certificates — request early in design phase. Had to consider Vigortronix as pin-compatible second source due to availability concerns. Always qualify 2+ sources for safety-critical power supplies.",
    type: "tip",
    status: "approved",
    addedDate: "2026-02-28",
  },

  // ── FullVision / Trackmaster Medical Treadmill Notes (from Slack archive 2019-2025) ──

  {
    id: "cn-022",
    partNumber: "PIC24FJ64GA006",
    note: "Main MCU for FullVision Trackmaster treadmill. Flash pseudo-EEPROM at address 0x9800. CRITICAL: All interrupts (GIE=0) MUST be disabled during flash write sequence — writing with interrupts enabled causes Address Error Trap after ~200 writes, resetting the MCU. Each bank write takes ~50ms, full save ~142ms. CPU trap counter register useful for diagnosing flash write failures. When upgrading to PIC24FJ128GA306, EEPROM address moves to 0x14000 and flash write commands differ.",
    type: "warning",
    status: "approved",
    addedDate: "2026-02-28",
  },
  {
    id: "cn-023",
    partNumber: "PIC24FJ128GA306",
    note: "Upgraded MCU for FullVision Trackmaster. Flash pseudo-EEPROM at address 0x14000 (NOT 0x9800 like the PIC24FJ64GA006). Flash write command opcodes differ from the 64K variant despite same register names. Must review Microchip data sheet sections on flash programming carefully when porting. Compile-time checks recommended to validate EEPROM addresses match the target part.",
    type: "warning",
    status: "approved",
    addedDate: "2026-02-28",
  },
  {
    id: "cn-024",
    partNumber: "BSS84P",
    note: "CORRECT P-channel MOSFET for FullVision magnetic pull tether safety circuit Q1 position. SOT-23 package, marked 'SP.' or 'YBs' on the part. DO NOT substitute IRLML6402 (marked 'EABN9') — it causes safety-critical latch-up where the tether fails to stop the treadmill. 320 of 568 boards were affected by this wrong-part issue. Visual inspection of Q1 marking is mandatory on incoming boards.",
    type: "warning",
    status: "approved",
    addedDate: "2026-02-28",
  },
  {
    id: "cn-025",
    partNumber: "IRLML6402",
    note: "WARNING: DO NOT USE as substitute for BSS84P in magnetic pull tether circuit. Although both are SOT-23 P-channel MOSFETs, the IRLML6402 (marked 'EABN9') has different Vgs(th) characteristics that cause safety-critical latch-up — the tether relay stays energized regardless of tether state. This was an FDA-reportable issue on 320 medical treadmill boards.",
    type: "warning",
    status: "approved",
    addedDate: "2026-02-28",
  },
  {
    id: "cn-026",
    partNumber: "T9CP5A54-120",
    note: "Relay used in FullVision treadmill elevation and motor circuits. Contact isolation rated at only 1500V — INSUFFICIENT for IEC 60601 hipot testing at 4.3kV. When relays are de-energized during hipot, snubber capacitors across the contacts (C39/C40) create an AC leakage path that fails the test. Required external DPDT contactor to achieve hipot isolation. Do not rely on this relay for safety isolation in medical applications.",
    type: "warning",
    status: "approved",
    addedDate: "2026-02-28",
  },
  {
    id: "cn-027",
    partNumber: "TE-2118708-2",
    note: "TE Connectivity PCB-mount EMI shielding can (Faraday cage) used over LCD controller circuit on FullVision treadmill. Required to pass IEC 61000-4-2 ESD and radiated immunity testing. The LCD controller and its ribbon cable are particularly susceptible to ESD coupling. Mount with continuous solder to ground plane for best shielding effectiveness.",
    type: "tip",
    status: "approved",
    addedDate: "2026-02-28",
  },
  {
    id: "cn-028",
    partNumber: "HATF901ASDC12-1",
    note: "Hasco relay verified as drop-in substitute for RL0015 (elevation relay) in FullVision treadmill. Used during RL0015 shortage. Same coil voltage (12VDC), contact rating, and footprint. Verify contact isolation voltage meets application requirements before using in safety-critical paths.",
    type: "substitute",
    status: "approved",
    addedDate: "2026-02-28",
  },
  {
    id: "cn-029",
    partNumber: "RNV14FAL1M00",
    note: "Stackpole 1MΩ high-voltage resistor. Used in 4x configuration (4x 1MΩ) replacing 2x 2MΩ in FullVision 4th edition power supply ground resistor network. The change improved surge immunity but increased ground-to-earth voltage from 0.39 VAC to 8.40 VAC. Verify IEC 60601 touch current limits when changing ground network values.",
    type: "tip",
    status: "approved",
    addedDate: "2026-02-28",
  },

  // ── FullVision Quantum Drive / Motor Notes (from Slack archive quantum-guest-channel 2023) ──

  {
    id: "cn-030",
    partNumber: "MKV31F512",
    note: "NXP Kinetis V-series ARM Cortex-M4 MCU used in Quantum treadmill drive board (Rev A/R0B). 512KB flash. Programmable via J-Link (Segger) SWD interface — requires AC power on drive board for programming (3.3V header can't back-power the board reliably). J-Flash Lite (free) works; full J-Flash requires Segger license. MKV31F256 (256KB variant) requires different board revision (R0C) due to missing timer used for input capture — traces rerouted on R0C to support both processors with same binary. EduMini programmer confirmed compatible — pin 1 alignment critical, off-by-one-row on header causes VTarget=0.9V (wrong) vs 3.3V (correct).",
    type: "tip",
    status: "approved",
    addedDate: "2026-02-28",
  },
  {
    id: "cn-031",
    partNumber: "MKV31F256",
    note: "NXP Kinetis V-series 256KB variant. Drop-in for MKV31F512 ONLY on Rev C (R0C) drive boards — the 256KB part is missing one timer peripheral used for input capture, requiring PCB trace rerouting. R0C board supports EITHER processor with same binary. When programming with J-Flash Lite, must select MKV31F256 as target device (not MKV31F512). Drive firmware version reporting: v4.x for 512KB processor, v5.x for 256KB processor. Silkscreen label on board identifies revision (Rev A = old pinout/512K only, Rev B = new pinout/either processor).",
    type: "warning",
    status: "approved",
    addedDate: "2026-02-28",
  },
  {
    id: "cn-032",
    partNumber: "Quantum-QC201-Drive",
    note: "Quantum Development Corp QC201 BLDC motor drive for medical treadmill. Serial communication: half-duplex UART at ~50 chars/sec each way, 200ms inter-message delay, up to 4-second response timeout, ~60Hz polling rate. Fault codes: 1=overcurrent (self-clearing in hardware!), 2048=invalid hall state, 4096=overacceleration (>2.5mph/sec), 8192=brake temperature. mc_current units are tenths of an amp. mc_fault=1 (overcurrent) is the ONLY fault that self-clears without disable/enable cycle. Disable then re-enable clears all other faults. Stiffness parameter repurposed as UVW fault counter in production firmware. Freemaster 3.2 (NXP) used for real-time variable monitoring via J-Link.",
    type: "tip",
    status: "approved",
    addedDate: "2026-02-28",
  },
  {
    id: "cn-033",
    partNumber: "Tru-Tech-BLDC-Motor",
    note: "16-pole BLDC motor with integrated encoder (A/B/Z quadrature + U/V/W commutation halls). Hipot tested at 1750VDC with 10uA leakage. Encoder commutation signals should align with line-to-line voltage zero crossings per app note. If all 3 commutation signals are inverted (180 degrees off), the motor WILL run away — this appears as a valid hall state (1-6) but creates positive feedback in the speed controller. Swapping 2 of 3 motor phases does NOT reproduce the runaway — just causes groaning and overcurrent. The mis-tuned motor had small particles in the shipping box suggesting mechanical encoder damage. Capacitive coupling from motor frame to encoder signals can cause spurious hall transitions — a ground cable from motor frame to drive ground plane eliminates this.",
    type: "warning",
    status: "approved",
    addedDate: "2026-02-28",
  },
  {
    id: "cn-034",
    partNumber: "ESP32-C3-DEVKITC-02",
    note: "Considered for standalone OTG programmer for MKV31F512 treadmill drive boards. Can probe the MKV31F via SWD using Adafruit_DAP library — confirmed reading flash size (0x80000 = 512KB) and device ID. 3.3V current from J-Link header: ~85mA for drive board alone plus programmer circuit current. WiFi should be disabled to stay under 50mA budget for the programmer. CMSIS-DAP and pyOCD (open source) are good references for understanding SWD protocol — ~25K transactions to upload a small binary.",
    type: "tip",
    status: "approved",
    addedDate: "2026-02-28",
  },
  {
    id: "cn-035",
    partNumber: "CSK35PP",
    note: "One-way bearing / freewheel clutch / backstop. Considered as a mechanical safety device for treadmill belt to prevent reverse rotation (which occurs during motor runaway from inverted encoder). Could provide last-resort physical protection against backward belt movement. Not implemented — software/firmware solutions pursued instead.",
    type: "tip",
    status: "approved",
    addedDate: "2026-02-28",
  },

  // ── SBI (Stove Builder International) Component Notes (from Slack archive 2015-2024) ──

  {
    id: "cn-036",
    partNumber: "24AA32A",
    note: "Microchip I2C EEPROM, 32Kbit, industrial temp (-40C to +85C). Rated 1M write cycles per page at 25C, temperature-derated. CRITICAL: Each individual byte write internally causes a full 32-byte page rewrite — one byte write consumes one write cycle for ALL 32 bytes in that page. Always use page writes, never byte writes. In SBI pellet stove controllers, byte-at-a-time writes exhausted cells in ~2 years. Also: NEVER share I2C bus lines with parallel LCD data bus — SDA/SCL on bits 8-9 of 16-bit LCD bus caused corruption during display updates. Use 3-bank redundancy with checksums. Store write counter at EEPROM addresses for field diagnostics. Timed saves every 10+ minutes, never SAVE_IMMEDIATE for frequently changing state.",
    type: "warning",
    status: "approved",
    addedDate: "2026-03-02",
  },
  {
    id: "cn-037",
    partNumber: "BTA12-600BWRG",
    note: "STMicro 12A 600V triac, TO-220. Tj max 125°C, Rth(j-c) 2.3°C/W. CRITICAL: Do NOT use on multi-tap fan motors where unpowered taps see transformer-coupled backfeed voltage exceeding 120VAC. Fails SHORT (not open), causing cascade failure of partner triac sharing alternating half-cycles. At 10A load, max case temp ~99°C. SBI replaced 92 power boards in 2020 due to this failure mode. Gate drive resistors upgraded from 100Ω 1/2W → 180Ω 2/3W pulse-withstanding → 220Ω — none solved the root cause. Use relays for full-on taps, reserve triacs only for phase-angle controlled outputs.",
    type: "warning",
    status: "approved",
    addedDate: "2026-03-02",
  },
  {
    id: "cn-038",
    partNumber: "T3035H-6I",
    note: "STMicro 30A 800V triac, TO-247 or similar. Tj max 150°C, Rth(j-c) 1.9°C/W. Preferred replacement for BTA12-600BWRG on SBI relay hybrid board. At 4A, max Pdiss ~3.3W, max case temp ~143°C. Better availability and cost than Q6035RH5 (35A Littelfuse). Tested in Alterna-II at ~80°C on speed 1 (worst case, lowest airflow) and ~90°C at ~8A in Max Caddy. Approved for production.",
    type: "tip",
    status: "approved",
    addedDate: "2026-03-02",
  },
  {
    id: "cn-039",
    partNumber: "T1620T",
    note: "STMicro 16A 800V triac. Drop-in upgrade for BTA12-600BWRG on existing triac boards. Temperature improved from 293°F to 237°F on setting 5 (no airflow), and 248°F to 184°F on setting 3. Good field results as a rework solution. Not as effective as custom heatsink (186°F) or relay hybrid board (eliminates root cause), but simplest field repair.",
    type: "tip",
    status: "approved",
    addedDate: "2026-03-02",
  },
  {
    id: "cn-040",
    partNumber: "PIC18F24K22",
    note: "Microchip PIC18F series, pin-compatible substitute for PIC18F26K22 during chip shortage. CRITICAL: POWER116.ROM firmware compiled for PIC18F26K22 will NOT run on PIC18F24K22 — causes continuous reboot loop (bricked). Since board is constantly rebooting, bootloader cannot receive commands to recover. Must compile separate firmware, change bootloader command from BOOT to LOAD, report version 1.16 to prevent LCD auto-update, and use different board sticker/part number to visually distinguish. Same-family pin-compatible ≠ firmware-compatible.",
    type: "warning",
    status: "approved",
    addedDate: "2026-03-02",
  },
  {
    id: "cn-041",
    partNumber: "3906-PNP",
    note: "General-purpose PNP transistor used as high-side driver for resistive touchscreen ADC measurement in SBI LCD boards. Component lot variation (same part number, different lot code) shifts the untouched screen ADC reading from ~1015 to ~1003 out of 1023 (10-bit). This shift can move the reading inside the 'touched' threshold (>1005), causing phantom touches and double-click behavior. CAL_DELTA firmware value must accommodate lot-to-lot variation. Changing to a different lot code sometimes fixes the issue — the variation is within-spec but causes system-level failure.",
    type: "warning",
    status: "approved",
    addedDate: "2026-03-02",
  },
  {
    id: "cn-042",
    partNumber: "RXE300",
    note: "Polyswitch/PTC resettable fuse, 3A rating at 25°C. Derates to ~2.3A at 50°C ambient (77% of rated hold current). Self-heats progressively — resistance increases gradually, causing voltage droop before full trip. Creates confusing intermittent symptoms that mimic firmware bugs (system dies, restarts when PTC cools). Diagnostic: tripped PTC is noticeably hotter than surrounding components. Thermal camera recommended for diagnosis. Does NOT reset by just cycling power — only resets when current drops AND device cools.",
    type: "warning",
    status: "approved",
    addedDate: "2026-03-02",
  },
  {
    id: "cn-043",
    partNumber: "V150LA20A",
    note: "150V MOV (Metal Oxide Varistor) for 120VAC input overvoltage protection. Used on SBI power board (V1 position). LIMITATION: Response time insufficient for short high-frequency spikes from generators or AC inverters — spikes can pass through before MOV begins conducting. Pair with TVS diode on DC side for fast clamping. MOV degrades with each transient event; may need periodic replacement in high-transient environments. MOV + reduced PTC strategy: size PTC so MOV clamping current exceeds PTC trip current.",
    type: "warning",
    status: "approved",
    addedDate: "2026-03-02",
  },
  {
    id: "cn-044",
    partNumber: "HATF901AS30DC12-1-ISN",
    note: "Relay used on SBI relay hybrid triac board (PCBLF0467). Verify coil voltage compatibility with rectified supply — original oil output relay had series resistance too high, preventing reliable actuation. Fix: changed to 24VDC coil with adjusted dropping resistor to reduce heat. When substituting relays, verify not just contact rating and coil voltage but also coil current, turn-on delay (~9.2ms measured), and back-EMF characteristics during de-energization.",
    type: "tip",
    status: "approved",
    addedDate: "2026-03-02",
  },
  {
    id: "cn-045",
    partNumber: "RP2040",
    note: "Raspberry Pi RP2040 microcontroller, used as PIC32 replacement on SBI PicoLCD boards. No EEPROM — all parameter storage must use internal flash with wear-leveling consideration. Longer boot time than PIC32, which affects power-loss recovery timing (capacitor charge detection for short power loss). USB Virtual COM Port (115200,N,8,1) provides invaluable debug output unavailable on PIC32. Firmware filename must be 'uSDSBIAPP.ROM' (not 'SBIAPP.ROM') to prevent cross-loading PIC firmware. Version convention: PIC v0.44 → Pico v1.44 (major +1, minor matches).",
    type: "tip",
    status: "approved",
    addedDate: "2026-03-02",
  },
];
