import { DesignRule } from "../types/index.js";

// ── Your team's design rules and conventions ──
// These get checked automatically when planning schematics
// and flagged in the check-design-rules tool.

export const designRules: DesignRule[] = [
  // ── Power Integrity ──
  {
    id: "pwr-001",
    category: "power-integrity",
    rule: "Every IC VDD pin gets a 100nF X7R ceramic within 3mm and a 10uF bulk within 10mm",
    reasoning: "Standard decoupling practice. Y5V ceramics lose too much capacitance at operating voltage.",
    severity: "must",
    status: "approved",
    addedDate: "2026-02-28",
  },
  {
    id: "pwr-002",
    category: "power-integrity",
    rule: "Power trace width minimum 20mil for signals under 500mA, 40mil for up to 1A",
    reasoning: "Based on 1oz copper, 10°C rise. Our standard stack-up.",
    severity: "must",
    status: "approved",
    addedDate: "2026-02-28",
  },

  // ── Component Selection ──
  {
    id: "comp-001",
    category: "component-selection",
    rule: "0402 resistors: max 50mW dissipation in production designs, use 0603 for anything above",
    reasoning: "Our reflow profile on line 2 runs at upper end of spec. 0402 at full rated power showed 3% field return rate on PROJ-2024-017.",
    severity: "must",
    applies: ["resistor"],
    exceptions: "Pull-ups and pull-downs exempt — negligible power dissipation",
    sourceProject: "PROJ-2024-017",
    status: "approved",
    addedDate: "2026-02-28",
  },
  {
    id: "comp-002",
    category: "component-selection",
    rule: "Prefer inventory-abundant parts over exact-match spec when both meet requirements",
    reasoning: "Reduces cost, avoids procurement delays, keeps feeders loaded",
    severity: "should",
    status: "approved",
    addedDate: "2026-02-28",
  },

  // ── Layout ──
  {
    id: "lay-001",
    category: "layout",
    rule: "ESP32 antenna keep-out: 15mm ground-plane clearance, stitching vias every 2mm at boundary",
    reasoning: "Per Espressif hardware design guide. Violating this degrades WiFi by 6-10dBm.",
    applies: ["ESP32-S3", "ESP32-C3", "ESP32-C6", "ESP32-S2"],
    severity: "must",
    status: "approved",
    addedDate: "2026-02-28",
  },

  // ── EMC ──
  {
    id: "emc-001",
    category: "emc",
    rule: "All external connectors must have ESD protection on signal lines",
    reasoning: "Required for CE/FCC certification. Failed on PROJ-2023-011 without it.",
    severity: "must",
    sourceProject: "PROJ-2023-011",
    status: "approved",
    addedDate: "2026-02-28",
  },

  // ── Manufacturing ──
  {
    id: "mfg-001",
    category: "manufacturing",
    rule: "Minimum 3 fiducials per board — 2 global + 1 local near fine-pitch components",
    reasoning: "Our pick-and-place requires 2 global fiducials minimum. Third local fiducial improves placement accuracy for QFN/BGA.",
    severity: "must",
    status: "approved",
    addedDate: "2026-02-28",
  },
  {
    id: "mfg-002",
    category: "manufacturing",
    rule: "Test points on all power rails and critical signals — 1mm pad minimum",
    reasoning: "Required for bed-of-nails testing on our ICT fixture",
    severity: "should",
    status: "approved",
    addedDate: "2026-02-28",
  },

  // ── Carter-Hoffmann M-Series Rules (from Slack archive 2020-2025) ──

  {
    id: "sig-001",
    category: "signal-integrity",
    rule: "Digital communication over cables MUST use shielded twisted pair (CAT-5e/RJ45). Never use flat telco (RJ11) for shift register clock/data signals.",
    reasoning: "Years of intermittent flicker and signal integrity failures across entire M-Series product line traced to unshielded flat telco cables. RJ11 cables have no shielding, no twisted pairs, inconsistent manufacturing quality, and wildly variable capacitance between manufacturers and batches.",
    sourceProject: "Carter-Hoffmann M-Series",
    severity: "must",
    status: "approved",
    addedDate: "2026-02-28",
  },
  {
    id: "sig-002",
    category: "signal-integrity",
    rule: "Route digital signal cables AWAY from AC voltage sources. Maintain minimum 50mm separation. Use ferrite coils on signal wires near power entry.",
    reasoning: "AC muffin fan (208V) EMI coupled into DC supply through adjacent cable routing, causing false switching and voltage spikes that destroyed display board ICs at Popeyes field installation.",
    sourceProject: "Carter-Hoffmann Popeyes Field Failure",
    severity: "must",
    status: "approved",
    addedDate: "2026-02-28",
  },
  {
    id: "mfg-003",
    category: "manufacturing",
    rule: "When specifying connectors for production cables, name exact manufacturer and part number. Document crimping procedure including insulation strip length (~1/4\"), strain relief engagement, and connector alignment.",
    reasoning: "Cable quality variations caused years of field failures. Outer insulation stripped too far back, strain relief not engaged, connector alignment off — all contributed to intermittent communication failures on shift register lines.",
    applies: ["RJ11", "RJ45", "JST-PH"],
    sourceProject: "Carter-Hoffmann M-Series (rma_flicker)",
    severity: "must",
    status: "approved",
    addedDate: "2026-02-28",
  },
  {
    id: "mfg-004",
    category: "manufacturing",
    rule: "Power supply boards MUST be tested at actual worst-case load for the intended application, not just nominal. For dual-transformer variants, test at double the single-transformer load.",
    reasoning: "FGLF0604-01 PSU boards failed after 30-60 min in M343 passthrough cabinets because dual-transformer load was nearly double what single-transformer test procedure covered.",
    sourceProject: "Carter-Hoffmann M343",
    severity: "must",
    status: "approved",
    addedDate: "2026-02-28",
  },
  {
    id: "rel-001",
    category: "reliability",
    rule: "Plan bootloader flash size for maximum expected future needs from the start. Reserve at least 2x the initial bootloader size.",
    reasoning: "Increasing bootloader from 19KB to 24KB for ConnectWare support shifted the application start address, making firmware images incompatible. Required separate part numbers (FGLF0605-01 vs -02) and version numbering schemes.",
    sourceProject: "Carter-Hoffmann ConnectWare Integration",
    severity: "should",
    status: "approved",
    addedDate: "2026-02-28",
  },
  {
    id: "rel-002",
    category: "reliability",
    rule: "When removing a state from a firmware state machine, grep the ENTIRE codebase for every reference — transitions into, out of, and guards checking for that state. Remove ALL of them.",
    reasoning: "Removing PROGRAM_ADJUST mode without cleaning all references caused display freeze when buttons were pressed during NOT_AT_SETPOINT state. The state machine transitioned to a state that no longer existed.",
    sourceProject: "Carter-Hoffmann WAWA v3.03",
    severity: "must",
    status: "approved",
    addedDate: "2026-02-28",
  },
  {
    id: "comp-003",
    category: "component-selection",
    rule: "When substituting logic IC speed grades (e.g., HC vs HCS series), full regression testing across ALL board configurations is mandatory. Faster is not always better.",
    reasoning: "Swapping HC08 AND gates to faster HCS08 fixed display flicker but broke button detection on downstream single-window displays. Required stocking two variants depending on configuration.",
    applies: ["HC08", "HCS08"],
    sourceProject: "Carter-Hoffmann M-Series (rma_flicker)",
    severity: "must",
    status: "approved",
    addedDate: "2026-02-28",
  },
  {
    id: "comp-004",
    category: "component-selection",
    rule: "Set NTC thermistor short-detection threshold to 500 ohm (not 1000 ohm) to avoid false errors in cold environments. 1000 ohm corresponds to ~32°F which is a realistic startup temperature.",
    reasoning: "Units on loading docks and unheated kitchens threw false short errors on startup with 1000 ohm threshold. Changed to 500 ohm in firmware v3, allowing minimum temperature reading down to -125°C.",
    applies: ["NTC-thermistor"],
    sourceProject: "Carter-Hoffmann NTX Cook-and-Hold",
    severity: "should",
    status: "approved",
    addedDate: "2026-02-28",
  },
  {
    id: "comp-005",
    category: "component-selection",
    rule: "Derate TRIACs to 5A maximum in production despite higher datasheet ratings. Heatsink required for continuous-duty heater outputs.",
    reasoning: "BTA12-600BWRG and T1235-600G-TR both rated 12A but production boards use 5A max. Higher current requires better thermal management than typical PCB mounting provides.",
    applies: ["BTA12-600BWRG", "T1235-600G-TR"],
    sourceProject: "Carter-Hoffmann M-Series",
    severity: "must",
    status: "approved",
    addedDate: "2026-02-28",
  },

  // ── Devon-REC / Nidek Battery Pack Rules (from Slack archive 2019-2025) ──

  {
    id: "pwr-003",
    category: "power-integrity",
    rule: "Battery monitor/protection ICs (BQ294700, etc.) MUST be powered through the final cell connection switch. Never power a BMS monitor IC before all cells are present.",
    reasoning: "Floating cell sense inputs cause voltages to exceed overvoltage thresholds, triggering fuse blow outputs and latching permanent faults. This destroyed chemical fuses on Nidek packs during assembly.",
    applies: ["BQ294700", "BQ294711"],
    sourceProject: "Devon-REC Nidek Battery Pack",
    severity: "must",
    status: "approved",
    addedDate: "2026-02-28",
  },
  {
    id: "emc-002",
    category: "emc",
    rule: "For battery charger designs using >500kHz buck converters, add RC snubber to FET output before the inductor and series gate resistance on high-side FET. Use 4-layer PCB with GND on layers 2-3.",
    reasoning: "1MHz BQ24610 charger failed CISPR11 Class B emissions by 28dB at 133MHz. Reducing charge current doesn't help — switching rise/fall times stay the same. Must address EMI at the source with snubbers, gate resistance, and minimized current loops.",
    applies: ["BQ24610", "BQ40Z60"],
    sourceProject: "Devon-REC Nidek Battery Pack",
    severity: "must",
    status: "approved",
    addedDate: "2026-02-28",
  },
  {
    id: "mfg-005",
    category: "manufacturing",
    rule: "BMS test fixtures MUST use permanent soldered connections with inline switches. Never use alligator clips for BMS cell connections.",
    reasoning: "Alligator clips create intermittent contact resistance causing momentary open circuits. BMS protection ICs interpret these as overvoltage events and trigger permanent faults. Switching from clips to soldered connections improved test yield from ~60% to nearly 100%.",
    sourceProject: "Devon-REC Nidek Battery Pack",
    severity: "must",
    status: "approved",
    addedDate: "2026-02-28",
  },
  {
    id: "rel-003",
    category: "reliability",
    rule: "BQ fuel gauge golden SREC creation sequence: firmware → chemistry → parameters → LT_FLUSH → LT_RESET → PF_CLEAR → BBR_CLEAR → RESET → save SREC. Do NOT enable FETs, fuse, gauge, or protections in the golden file.",
    reasoning: "Programming in wrong order overwrites chemistry with firmware defaults. Enabling safety systems before cell assembly causes faults during manufacturing. FET_EN and GAUGE_EN should be post-assembly activation steps.",
    applies: ["BQ40Z60", "BQ40Z50"],
    sourceProject: "Devon-REC Nidek Battery Pack",
    severity: "must",
    status: "approved",
    addedDate: "2026-02-28",
  },
  {
    id: "prot-001",
    category: "protection",
    rule: "Set BMS short circuit protection delay > 0μs for applications with inductive or incandescent loads. Instantaneous 5A loads trip short circuit detection even when steady-state current is within limits.",
    reasoning: "Tail lamp inrush current exceeded 8.88A short circuit threshold (44.4mV / 5mΩ sense resistor) with 0μs delay, even though steady-state was only 5A. O2 concentrator with gradual ramp worked fine. Test houses must ramp loads over ~5 seconds.",
    applies: ["BQ40Z60", "BQ40Z50"],
    sourceProject: "Devon-REC Nidek Battery Pack",
    severity: "should",
    status: "approved",
    addedDate: "2026-02-28",
  },
  {
    id: "pwr-004",
    category: "power-integrity",
    rule: "Use net ties to connect analog GND and power GND at a single defined point on BMS PCBs. This controls where high-current power return flows.",
    reasoning: "BMS boards handle both sensitive analog measurements (cell voltages, current sense) and high-current power paths. Separating grounds with a single tie point prevents noisy power currents from corrupting analog measurements.",
    sourceProject: "Devon-REC Nidek Battery Pack",
    severity: "should",
    status: "approved",
    addedDate: "2026-02-28",
  },
  {
    id: "rel-004",
    category: "reliability",
    rule: "Set software COV (cell overvoltage) threshold at least 100mV BELOW the hardware overvoltage detector (e.g., BQ771605DPJR at 3.85V → set COV to 3750mV). Software should catch overvoltage before hardware fires.",
    reasoning: "If software COV is too close to hardware trip point, the hardware detector fires first causing a permanent fault that requires manual clearing. Software protection is recoverable; hardware protection may not be.",
    applies: ["BQ771605DPJR", "BQ40Z50"],
    sourceProject: "Devon-REC U1 Battery Pack",
    severity: "must",
    status: "approved",
    addedDate: "2026-02-28",
  },

  // ── Polyvance Plastic Welder Rules (from Slack archive 2019-2025) ──

  {
    id: "prot-002",
    category: "protection",
    rule: "UL-listed products with heating elements MUST have a hardware safety cutoff (snap disc thermostat or RTD + comparator driving a relay) that is independent of software. The relay must be normally-open (fail-safe).",
    reasoning: "UL requires defense-in-depth: software monitors temperature during normal operation, but a separate hardware mechanism must independently prevent dangerous overheating if software fails. Software-only thermal protection is insufficient for UL listing.",
    sourceProject: "Polyvance Plastic Welder",
    severity: "must",
    status: "approved",
    addedDate: "2026-02-28",
  },
  {
    id: "sig-003",
    category: "signal-integrity",
    rule: "Route zero-crossing detection traces minimum 5mm from shift register clock/data lines on PCB. Add RC filtering (10KΩ + 100nF) on zero-crossing comparator input.",
    reasoning: "Fast TTL edges from shift register clock/data capacitively couple into high-impedance zero-crossing detection input, causing false TRIAC triggering. Problem worsens with longer ribbon cables. Same root cause as Carter-Hoffmann M-Series cable noise.",
    applies: ["BTA12-600BW", "BTA12-600BWRG"],
    sourceProject: "Polyvance Plastic Welder (chevy)",
    severity: "must",
    status: "approved",
    addedDate: "2026-02-28",
  },
  {
    id: "rel-005",
    category: "reliability",
    rule: "Raspberry Pi deployments in embedded products must include advance power-down circuit and read-only root filesystem. Budget for ~5% annual SD card failure rate.",
    reasoning: "RPi writes to SD card frequently (logs, swap, journals). Abrupt power loss during write corrupts filesystem. Industrial environments have frequent power interruptions. Class 10 SD cards not designed for embedded write endurance.",
    applies: ["RPi-Zero-W", "RPi-3B", "RPi-4B"],
    sourceProject: "Polyvance Plastic Welder (bugatti)",
    severity: "must",
    status: "approved",
    addedDate: "2026-02-28",
  },
  {
    id: "mfg-006",
    category: "manufacturing",
    rule: "Stepper motor flow valves require rewind-to-home calibration on every power-up. Production flow calibration must be 2-point per-unit, approaching setpoints from the same direction to eliminate hysteresis.",
    reasoning: "Stepper motors have no absolute position feedback. Mechanical valve hysteresis means flow differs depending on approach direction. Unit-to-unit variation in valve seating and motor step accuracy requires individual calibration.",
    applies: ["4118L-07P"],
    sourceProject: "Polyvance Plastic Welder (plasticwelder)",
    severity: "must",
    status: "approved",
    addedDate: "2026-02-28",
  },
  {
    id: "pwr-005",
    category: "power-integrity",
    rule: "For 5-20W embedded power supplies, prefer board-mount AC-DC modules (Meanwell IRM series or equivalent) over discrete transformer + rectifier + regulator designs.",
    reasoning: "Board-mount modules provide universal input (85-264VAC), integrated safety isolation, UL/CE certification, smaller footprint, and lower BOM cost ($3-8). Eliminates need for separate 120V/240V variants. Only use discrete transformer approach for custom voltage, high power, or specific EMI requirements.",
    sourceProject: "Polyvance Plastic Welder (plasticwelder)",
    severity: "should",
    status: "approved",
    addedDate: "2026-02-28",
  },
  {
    id: "rel-006",
    category: "reliability",
    rule: "OTA firmware update infrastructure must have automated SSL certificate renewal. Expired certs silently break all field updates.",
    reasoning: "Polyvance welder fleet lost OTA update capability when SSL certificate expired on the update server. Units reported connection errors but no clear indication of cert expiry. Required manual server-side renewal before any units could update.",
    sourceProject: "Polyvance Plastic Welder (bugatti)",
    severity: "must",
    status: "approved",
    addedDate: "2026-02-28",
  },

  // ── FullVision / Trackmaster Medical Treadmill Rules (from Slack archive 2019-2025) ──

  {
    id: "prot-003",
    category: "protection",
    rule: "Safety-critical transistor substitutions MUST be verified by visual marking inspection on every incoming board. Document expected part markings in the incoming inspection procedure.",
    reasoning: "320 of 568 treadmill boards shipped with wrong Q1 (IRLML6402 'EABN9' instead of BSS84P 'SP.'/'YBs'), causing safety-critical magnetic tether latch-up. FDA-reportable issue. Visual marking check would have caught this at incoming inspection.",
    applies: ["BSS84P", "IRLML6402"],
    sourceProject: "FullVision Trackmaster Treadmill",
    severity: "must",
    status: "approved",
    addedDate: "2026-02-28",
  },
  {
    id: "rel-007",
    category: "reliability",
    rule: "PIC24FJ flash pseudo-EEPROM writes MUST disable ALL interrupts (GIE=0) for the entire write sequence. Accept ~142ms of system unresponsiveness during saves.",
    reasoning: "Interrupts firing during PIC24FJ flash programming sequence corrupt the program counter, causing Address Error Trap and MCU reset. Failure occurs after ~200 writes with interrupts enabled. Each bank write takes ~50ms.",
    applies: ["PIC24FJ64GA006", "PIC24FJ128GA306"],
    sourceProject: "FullVision Trackmaster Treadmill",
    severity: "must",
    status: "approved",
    addedDate: "2026-02-28",
  },
  {
    id: "test-001",
    category: "testability",
    rule: "Snubber capacitors across relay contacts MUST be disconnectable (test points or jumpers) for hipot testing. Alternatively, add an external contactor to isolate the relay+snubber network during hipot.",
    reasoning: "Snubber capacitors C39/C40 across relay contacts create an AC leakage path from mains to motor circuits that fails IEC 60601 4.3kV hipot testing even with relays de-energized. Relay contact isolation (1500V on T9CP5A54-120) is also insufficient for 4.3kV.",
    applies: ["T9CP5A54-120"],
    sourceProject: "FullVision Trackmaster Treadmill",
    severity: "must",
    status: "approved",
    addedDate: "2026-02-28",
  },
  {
    id: "emc-003",
    category: "emc",
    rule: "All exposed metal hardware touchable by the user MUST have a dedicated low-impedance ground bond wire to chassis ground. Verify with milliohm meter — long or thin wires have too much inductance to shunt ESD pulses.",
    reasoning: "ESD test at -4kV contact discharge to magnetic tether mounting bolt crashed the treadmill MCU. Adding a heavy gauge ground wire directly to chassis ground bus fixed the failure. High-impedance or long ground paths are ineffective against fast ESD transients.",
    sourceProject: "FullVision Trackmaster Treadmill",
    severity: "must",
    status: "approved",
    addedDate: "2026-02-28",
  },
  {
    id: "prot-004",
    category: "protection",
    rule: "Low-current safety switches (pull tethers, e-stops) require minimum 600ms debounce timer AND either gold-plated contacts or a 1mA minimum wetting current to prevent contact fretting failures.",
    reasoning: "Contact fretting/oxidation on low-current safety switches was the dominant intermittent failure mode on medical treadmills for years. Standard tin-plated contacts at microamp sensing currents build up oxide layers from vibration-induced micro-motion. 600ms debounce + wetting current or gold contacts eliminates the issue.",
    applies: ["pull-tether-switch", "e-stop-switch"],
    sourceProject: "FullVision Trackmaster Treadmill",
    severity: "must",
    status: "approved",
    addedDate: "2026-02-28",
  },
  {
    id: "rel-008",
    category: "reliability",
    rule: "Medical device serial communication protocols MUST implement a watchdog timeout (≤2.5s per IEC 60601) with automatic transition to safe state. The safe state must stop all motion and return to a known position.",
    reasoning: "GE CASE system occasionally paused serial communication for >2.5s during screen transitions, triggering CDSE (Communication Disconnect Safety Event). The timeout cannot be extended for safety reasons — the host system must maintain polling. Document the polling requirement prominently in integration guides.",
    sourceProject: "FullVision Trackmaster Treadmill",
    severity: "must",
    status: "approved",
    addedDate: "2026-02-28",
  },
  {
    id: "rel-009",
    category: "reliability",
    rule: "Do not use sprintf() or printf() family functions in real-time firmware on PIC MCUs. Use dedicated integer-to-ASCII conversion functions instead.",
    reasoning: "sprintf() takes 25ms per call on PIC24FJ at 16 MIPS — it pulls in floating-point support even for integer formatting. Multiple calls per loop iteration caused communication timeouts and missed deadlines. Custom itoa() completes in <1ms.",
    applies: ["PIC24FJ64GA006", "PIC24FJ128GA306"],
    sourceProject: "FullVision Trackmaster Treadmill",
    severity: "must",
    status: "approved",
    addedDate: "2026-02-28",
  },
  {
    id: "sig-004",
    category: "signal-integrity",
    rule: "Hall effect speed sensors need a startup blanking period (2-3 seconds) after motor start to ignore partial pulses from magnet proximity at rest position.",
    reasoning: "Belt magnet parked near/over hall sensor at power-on produces a partial pulse counted as a full revolution, causing overspeed error (Error 5) or no-speed error (Error 6). Require 2 consecutive consistent readings before accepting speed value.",
    applies: ["hall-effect-sensor"],
    sourceProject: "FullVision Trackmaster Treadmill",
    severity: "should",
    status: "approved",
    addedDate: "2026-02-28",
  },
  {
    id: "test-002",
    category: "testability",
    rule: "RS-232 diagnostic loopback plugs must be bright colored, labeled 'REMOVE BEFORE OPERATION', and added to service close-out checklist. Firmware should detect TX=RX loopback and enter safe state.",
    reasoning: "A diagnostic loopback plug left on the RS-232 port caused a medical treadmill to run unattended for 32 hours — the treadmill's own transmissions were echoed back as valid commands, defeating the communication timeout safety.",
    sourceProject: "FullVision Trackmaster Treadmill",
    severity: "should",
    status: "approved",
    addedDate: "2026-02-28",
  },
  {
    id: "emc-004",
    category: "emc",
    rule: "Motor power wires require toroid inductors. Communication cables require clamp-on ferrite toroids. MOV surge protectors across motor terminals. This is the minimum EMI filter chain for DC motor drive systems.",
    reasoning: "FullVision treadmill EMC certification required a multi-stage filter chain: toroids on motor wires to suppress conducted emissions, MOVs for surge transients from motor commutation, and clamp toroids on serial communication cables to prevent radiated emissions from coupling into the comm lines.",
    sourceProject: "FullVision Trackmaster Treadmill (powersupply_edition4)",
    severity: "must",
    status: "approved",
    addedDate: "2026-02-28",
  },

  // ── FullVision Quantum Drive Rules (from Slack archive quantum-guest-channel 2023) ──

  {
    id: "prot-005",
    category: "protection",
    rule: "BLDC motor drives MUST implement both acceleration AND deceleration fault detection. The measured acceleration/deceleration limit (fault threshold) must be ABOVE the maximum commanded ramp rate to avoid nuisance trips, but below the physically dangerous threshold.",
    reasoning: "Quantum treadmill drive had 2.5mph/sec acceleration fault limit but 15mph/sec deceleration ramp, causing the fault to trip on every emergency stop. Must coordinate: accel ramp (1mph/sec) < decel ramp (4-5mph/sec) < fault threshold (adjustable, ~3-5mph/sec) < dangerous acceleration (~7mph/sec field incident).",
    applies: ["MKV31F512", "Quantum-QC201-Drive"],
    sourceProject: "FullVision Quantum Treadmill (quantum-guest-channel)",
    severity: "must",
    status: "approved",
    addedDate: "2026-02-28",
  },
  {
    id: "prot-006",
    category: "protection",
    rule: "Motor encoder hall signal validation at startup must verify the initial hall state is NOT the electrical inverse of expected. States 1-6 are all individually valid but an inverted set causes positive-feedback runaway. Validate by checking consistency over multiple samples AND checking that initial motion matches commanded direction.",
    reasoning: "A mis-tuned treadmill motor had all 3 commutation signals inverted by 180 degrees. Each individual state (1-6) passed the all-high/all-low validity check, but the inverted alignment caused the speed controller to apply positive torque when measuring negative RPM, creating a runaway to maximum speed. Motor ran in reverse from the controller's perspective.",
    applies: ["BLDC-motor", "MKV31F512"],
    sourceProject: "FullVision Quantum Treadmill (quantum-guest-channel)",
    severity: "must",
    status: "approved",
    addedDate: "2026-02-28",
  },
  {
    id: "emc-005",
    category: "emc",
    rule: "BLDC motor encoder cable shield MUST be connected to the motor frame AND to the drive board ground plane. The motor frame must have a low-impedance ground bond to the drive ground. Use star washer to penetrate powder coat on mounting hardware.",
    reasoning: "Unshielded/ungrounded motor encoder cables allow capacitive coupling from motor frame to encoder signals (UVW hall sensors and ABZ quadrature). This causes spurious hall state transitions that trigger 2048 faults and 4096 overacceleration faults. Grounding the motor frame to the drive ground plane via the existing but unused 4th blade connector on the motor cable eliminates the noise. A 0.2 milliohm or less resistance is the target. Star washers needed on powder-coated mounting hardware to ensure metal-to-metal contact.",
    applies: ["BLDC-motor", "Quantum-QC201-Drive"],
    sourceProject: "FullVision Quantum Treadmill (quantum-guest-channel)",
    severity: "must",
    status: "approved",
    addedDate: "2026-02-28",
  },
  {
    id: "rel-010",
    category: "reliability",
    rule: "Error/fault code priorities in firmware MUST be ordered by severity with motor controller hardware faults and acceleration errors taking precedence over derived errors like zero-speed or overspeed.",
    reasoning: "FullVision power supply firmware had incorrect error priority ordering where zero-speed error (ER3) was evaluated before motor controller fault (ER8). A motor controller fault that stopped the belt would be reported as ER3 (zero speed) because the belt stopped, masking the real root cause. Fixed priority: ER10 (overaccel) > ER8 (mc fault) > ER4 (mc overspeed) > ER3 (mc zero speed) > ER5/6 (external speed) > ER9 (start reject) > ER2 (elevation).",
    sourceProject: "FullVision Quantum Treadmill (quantum-guest-channel)",
    severity: "must",
    status: "approved",
    addedDate: "2026-02-28",
  },
  {
    id: "rel-011",
    category: "reliability",
    rule: "Firmware version numbering for field-upgradeable medical devices must include a sub-version that changes with EVERY build. Never release two different binaries with the same version number. Use separate version tracks for different hardware revisions.",
    reasoning: "Quantum treadmill firmware went through versions 1.19.99 through 1.19.106 (power supply) and v4.0 through v5.1 (drive). Confusion arose when v4.2 for 512KB processor (reported as 1026) and v5.0 for 256KB processor (reported as 1280) were both in production simultaneously. The calibration software's Quantum tab had to detect firmware subversion to display correctly. TM_Hero.srec vs TM_UPT.srec naming added further confusion. Each binary must have a unique, traceable version number.",
    sourceProject: "FullVision Quantum Treadmill (quantum-guest-channel)",
    severity: "must",
    status: "approved",
    addedDate: "2026-02-28",
  },
  {
    id: "test-003",
    category: "testability",
    rule: "Motor drive validation testing MUST include start/stop cycling at LOW target speeds (1-2 mph) as well as high speeds. Include at least 3x more start/stop cycles than the original high-speed-only test.",
    reasoning: "Quantum treadmills passed factory validation (high-speed focused, few start/stop cycles) but failed in clinical use at 1-1.7mph with 4096 overacceleration faults. Acceleration margins are tightest during startup at low speeds. Clinical use involves far more start/stop cycles than factory testing captured.",
    sourceProject: "FullVision Quantum Treadmill (quantum-guest-channel)",
    severity: "must",
    status: "approved",
    addedDate: "2026-02-28",
  },
  {
    id: "sig-005",
    category: "signal-integrity",
    rule: "When using pulse timing (time between encoder Z-pulses) for speed/acceleration calculation, use at minimum 0.25ms timer resolution. 1ms resolution is insufficient for accurate acceleration measurement at speeds above 5mph. Debounce with at least 2 consecutive measurements before acting on acceleration values.",
    reasoning: "FullVision treadmill firmware first attempted millisecond-resolution lookup tables (512 entries) for instantaneous acceleration in the timer ISR. At 15mph, pulse intervals are ~10ms giving only 10 discrete speed values. Single noise glitches created phantom 64mph/sec acceleration readings. Moving to 0.25ms resolution with main-loop circular buffer processing and minimum 50us inter-transition filtering eliminated false readings.",
    applies: ["PIC-SPSB", "hall-effect-sensor"],
    sourceProject: "FullVision Quantum Treadmill (quantum-guest-channel)",
    severity: "must",
    status: "approved",
    addedDate: "2026-02-28",
  },
  {
    id: "pwr-006",
    category: "power-integrity",
    rule: "PWM acceleration parameter in motor drives: lower number = faster acceleration, higher number = slower. The timer interrupt count determines how many 4kHz ticks pass before incrementing PWM by 1. Minimum value 20 (fastest: ~6mph/sec), default 160 (~0.4mph/sec), maximum 300 (slowest). Do not allow field configuration below 20.",
    reasoning: "FullVision treadmill PWM acceleration parameter is inverted from user expectation. At 4kHz interrupt rate with default value 160: 160 ticks * 0.25ms = 40ms per PWM increment. To reach 1000 PWM = 40 seconds. At minimum value 20: 5ms per increment, 1000 PWM in 5 seconds. Engineers repeatedly confused by the inverted relationship. Document clearly in all interfaces.",
    applies: ["PIC-SPSB"],
    sourceProject: "FullVision Quantum Treadmill (quantum-guest-channel)",
    severity: "should",
    status: "approved",
    addedDate: "2026-02-28",
  },

  // ── FullVision Burn-In / Quantum Control Integration Rules (from Slack archive burnin-functionaltest + quantumcontrol 2020-2024) ──

  {
    id: "emc-006",
    category: "emc",
    rule: "Motor POWER cable shields must be isolated from the system ground plane (use bleed-off resistor). This is distinct from motor ENCODER cable shields which should be grounded.",
    reasoning: "Direct motor power cable shield-to-ground connection fed BLDC commutation noise into console circuits, causing phantom button presses. Quantum Controls confirmed all EMC scans passed with power cable shield isolated. Motor encoder cable shield DOES need ground bonding for signal integrity (see emc-005).",
    applies: ["Tru-Tech-BLDC-Motor", "Quantum-QC201-Drive"],
    sourceProject: "FullVision Quantum Treadmill (quantumcontrol)",
    severity: "must",
    status: "approved",
    addedDate: "2026-02-28",
  },
  {
    id: "rel-012",
    category: "reliability",
    rule: "When bitbanging UART from a timer interrupt, choose a baud rate that divides evenly into the existing timer rate. Never change the timer interrupt rate to accommodate a new baud rate.",
    reasoning: "Changing PIC timer from 4kHz to 9600Hz for 9600 baud bitbanging cascaded into dozens of dependent parameter changes — speed ratios exceeding uint16 max (96000 > 65535), PWM timing, debounce, filter. Getting Quantum to use 4000 baud was far simpler and safer than changing the system timer.",
    applies: ["PIC24FJ64GA006", "PIC24FJ128GA306"],
    sourceProject: "FullVision Quantum Treadmill (quantumcontrol)",
    severity: "must",
    status: "approved",
    addedDate: "2026-02-28",
  },
  {
    id: "rel-013",
    category: "reliability",
    rule: "Debug UART output in production firmware MUST be non-blocking (DMA or buffered) and rate-limited. At 4000 baud, a 100-char message blocks for 250ms — enough to cause safety timeouts.",
    reasoning: "Verbose debug messages blocked the main processing loop, causing random belt stops, 30 speed changes logged in 15 seconds, and console flashing. Main loop could not service speed control or safety monitoring during UART TX wait.",
    sourceProject: "FullVision Quantum Treadmill (quantumcontrol)",
    severity: "must",
    status: "approved",
    addedDate: "2026-02-28",
  },
  {
    id: "prot-007",
    category: "protection",
    rule: "Motor startup MUST include PWM-limited soft-start period (~0.6% duty for 1.3 seconds) to prevent over-acceleration during alignment-to-rotation transition, especially under load.",
    reasoning: "Without startup PWM limiting, 100% ER10 failure rate with 500lb load at 98-180V. With 1.3s limit at 0.6% duty: 1500+ cycles with 1 possible error. Motor alignment-to-rotation transition creates a step change that triggers over-acceleration protection. LIMITSTARTUPACCELTIME=13.",
    applies: ["MKV31F512", "PIC-SPSB"],
    sourceProject: "FullVision Trackmaster Treadmill (burnin-functionaltest)",
    severity: "must",
    status: "approved",
    addedDate: "2026-02-28",
  },
  {
    id: "test-004",
    category: "testability",
    rule: "Calibration and validation procedures MUST be tested at worst-case low voltage (180V/50Hz), not just factory nominal (220V/60Hz). Max achievable speed drops from 16.4mph to 13.4mph at low voltage.",
    reasoning: "Calibration auto-populate threshold of 15.5mph could never be reached at 180V/50Hz. Calibration stalled and validation failed. Speed-to-PWM relationship is highly nonlinear above 70% duty cycle. The lower auto-populate threshold (14mph) and widened accuracy windows were needed.",
    sourceProject: "FullVision Trackmaster Treadmill (burnin-functionaltest)",
    severity: "must",
    status: "approved",
    addedDate: "2026-02-28",
  },
  {
    id: "sig-006",
    category: "signal-integrity",
    rule: "Motor encoder Z-pulse signals must be shielded and routed away from relay contacts and AC power. A single noise glitch at low motor speed doubles the apparent RPM, triggering over-acceleration protection.",
    reasoning: "Chattering relay near Z-pulse caused false ER10 errors within minutes. Without noise: 260+ clean cycles. At low speed, pulse intervals are ~100ms — one extra edge halves the apparent period and doubles the speed. ACCEL_DEBOUNCE=2 (4 revolutions) and speed-dependent limits mitigate but shielding prevents.",
    applies: ["hall-effect-sensor"],
    sourceProject: "FullVision Trackmaster Treadmill (burnin-functionaltest)",
    severity: "must",
    status: "approved",
    addedDate: "2026-02-28",
  },

  // ── SBI (Stove Builder International) Design Rules (from Slack archive 2015-2024) ──

  {
    id: "rel-014",
    category: "reliability",
    rule: "EEPROM writes MUST use page writes (32 bytes), never individual byte writes. A single byte write to a paged EEPROM counts as a full page-write cycle for all bytes in that page, reducing effective endurance by up to 32x.",
    reasoning: "SBI pellet stove LCD boards returned with EEPROM failures after ~2 years. The 24AA32A EEPROM was written one byte at a time, but each byte write internally rewrites the entire 32-byte page. Switching to page writes extended effective endurance by 32x.",
    applies: ["24AA32A"],
    sourceProject: "SBI Pellet Stove Controllers",
    severity: "must",
    status: "approved",
    addedDate: "2026-03-02",
  },
  {
    id: "rel-015",
    category: "reliability",
    rule: "Never share I2C EEPROM bus lines with any other active peripheral, especially parallel LCD data buses. If bus sharing is unavoidable, disable all other peripherals during EEPROM transactions.",
    reasoning: "SBI LCD board EEPROM SDA/SCL shared physical I/O pins (bits 8-9) with 16-bit parallel LCD data bus. LCD writes during EEPROM transactions corrupted data. A cost-reduction redesign removed the wrong EEPROM — the one NOT sharing I/O was removed. Lab testing: 1,500 failures on shared-bus section vs 0 failures after 1M+ writes on clean section.",
    applies: ["24AA32A"],
    sourceProject: "SBI Pellet Stove Controllers",
    severity: "must",
    status: "approved",
    addedDate: "2026-03-02",
  },
  {
    id: "rel-016",
    category: "reliability",
    rule: "Never use SAVE_IMMEDIATE for parameters that change frequently (thermostat state, fan speed, runtime counters). Use timed saves at 10-minute minimum intervals. Always power up into a known-safe state rather than restoring volatile state from EEPROM.",
    reasoning: "SBI Alterna-II logged 508 EEPROM writes/hour with thermostat cycling (control_state and fan_speed both set to SAVE_IMMEDIATE). At this rate, 1M cycles exhausted in ~52 days. Changing to timed saves reduced to 8 writes/hour (63x improvement). Target: minimum 5-6 year EEPROM lifespan.",
    sourceProject: "SBI Alterna-II Pellet Stove",
    severity: "must",
    status: "approved",
    addedDate: "2026-03-02",
  },
  {
    id: "rel-017",
    category: "reliability",
    rule: "Always zero ALL RAM on microcontroller powerup before using any variables. Never assume RAM is cleared to zero after reset.",
    reasoning: "SBI triac board: MCU RAM retained previous duty cycle values after 5-second power cycles. Phase-angle firing recalculation only triggered on value CHANGE. If retained value matched new target, no recalculation occurred and triac output never activated. ~50% failure rate on quick power cycles. Full RAM zero in v1.16 fixed it: 26/26 passes.",
    sourceProject: "SBI Alterna-II / Wood Furnace Controllers",
    severity: "must",
    status: "approved",
    addedDate: "2026-03-02",
  },
  {
    id: "pwr-007",
    category: "power-integrity",
    rule: "For multi-tap inductive loads (fan motors), use relays to isolate unused taps. Never leave triacs permanently connected to all taps — motor windings act as transformer, backfeeding voltage exceeding rated supply to unpowered taps.",
    reasoning: "SBI replaced 92 power boards in 2020. Multi-tap fan motor windings backfed voltage >120VAC to inactive taps. Triacs fail SHORT, causing cascade failure. Gate resistor upgrades (100Ω→180Ω→220Ω) did not solve the problem. Only relay isolation of unused taps eliminates the root cause. Speeds 5 and 6 were never phase-angle fired — relays are a natural fit.",
    applies: ["BTA12-600BWRG", "T3035H-6I"],
    sourceProject: "SBI Wood/Pellet Furnace Controllers",
    severity: "must",
    status: "approved",
    addedDate: "2026-03-02",
  },
  {
    id: "pwr-008",
    category: "power-integrity",
    rule: "Always add secondary-side overvoltage protection (TVS/transorb on DC side of rectifier) when using a switching regulator fed from a transformer. Primary-side MOV alone is insufficient for fast transients.",
    reasoning: "SBI Low-Cost Fan Limit board: relay switching creates voltage transients on shared 24VAC transformer. VR1 switching regulator (50VDC max input) failed catastrophically from instantaneous overvoltage. Primary MOV (150VAC) too slow for high-frequency spikes. TVS on DC side + reduced polyswitch provides self-resetting protection.",
    sourceProject: "SBI Low-Cost Fan Limit Board",
    severity: "must",
    status: "approved",
    addedDate: "2026-03-02",
  },
  {
    id: "pwr-009",
    category: "power-integrity",
    rule: "Design transformer-fed switching regulators for worst-case unloaded secondary voltage at maximum expected line voltage (130VAC). Ensure at least 30% margin on regulator Vin max.",
    reasoning: "SBI board: 24VAC transformer at 130VAC input produced 31.15VAC unloaded secondary. Rectified = ~44VDC, approaching 50VDC regulator max. Combined with transients from relay switching, exceeded Vin max and caused violent failure. Hammond BD2G transformer was the reference.",
    sourceProject: "SBI Low-Cost Fan Limit Board",
    severity: "must",
    status: "approved",
    addedDate: "2026-03-02",
  },
  {
    id: "prot-008",
    category: "protection",
    rule: "Implement zero-crossing detection for relay switching on shared AC power supplies. Relay coil de-energization at peak AC voltage creates transients that propagate to voltage regulators on the same transformer.",
    reasoning: "SBI boards: relay switching transients at peak voltage caused VR1 regulator failures. Zero-crossing relay synchronization (~9.2ms measured turn-on delay, varies part-to-part) significantly reduces transient magnitude. If relay delay variation exceeds ±4.1ms, zero-cross benefits are reduced but not eliminated. Cost: ~$0.20 per board.",
    sourceProject: "SBI Low-Cost Fan Limit Board",
    severity: "should",
    status: "approved",
    addedDate: "2026-03-02",
  },
  {
    id: "test-005",
    category: "testability",
    rule: "Production test procedures for polled multi-board systems MUST account for maximum communication latency (10+ seconds). Display clear 'waiting' indicators. Never judge output activation within a fixed short timeout.",
    reasoning: "SBI production testing had 50% false-failure rate on triac boards because testers didn't wait for full polling cycle. LCD→Link→Triac communication worst case: 10 seconds from button press to actual output change. Testers interpreted latency as board failure.",
    sourceProject: "SBI Alterna-II / Multi-product",
    severity: "must",
    status: "approved",
    addedDate: "2026-03-02",
  },
  {
    id: "sig-007",
    category: "signal-integrity",
    rule: "Line voltage measurement via transformer secondary MUST include per-output load compensation. Each active output causes 2-8V measurement drop. Provide user-adjustable calibration parameter.",
    reasoning: "SBI Alterna-II: unloaded measurement error 5V, but with ignition loads: 16V error (119V actual → 103V displayed). False low-voltage at 98V threshold with only 5V margin caused infinite 3-minute fan on/off cycle. Different rectifier diodes across board revisions add 10% variation. Use moving average filter (~90 seconds) and calibration parameter.",
    sourceProject: "SBI Alterna-II / Wood Furnace",
    severity: "should",
    status: "approved",
    addedDate: "2026-03-02",
  },
  {
    id: "rel-018",
    category: "reliability",
    rule: "Fuse ratings MUST protect the weakest downstream component, not just the wire gauge. For motor circuits with triacs rated at 5A continuous, a 12A fuse provides zero triac protection.",
    reasoning: "SBI triac board: each triac rated ~5A continuous but protected by 12A fuse. Fuse allowed sustained overcurrent that damaged triacs before blowing. For 1/4 HP motors (3.5A max), use 5A fast-blow fuse. 12A fuse only appropriate for 1/2 HP motors (>10A).",
    applies: ["BTA12-600BWRG"],
    sourceProject: "SBI Wood Furnace Controllers",
    severity: "must",
    status: "approved",
    addedDate: "2026-03-02",
  },
  {
    id: "emc-007",
    category: "emc",
    rule: "Continuously refresh shift register display outputs in firmware, even during 'off' states. EMI from motor/relay switching can corrupt latched data that persists until explicitly overwritten.",
    reasoning: "SBI Low-Cost Fan Limit board: LED display showed random segments when blower motor was running. Shift register latches corrupted by conducted EMI from motor/relay switching. Problem only appeared with loads connected, never on bench. Board mounted 1/4 inch from metal frame in PSG installations.",
    sourceProject: "SBI Low-Cost Fan Limit Board",
    severity: "should",
    status: "approved",
    addedDate: "2026-03-02",
  },
  {
    id: "prot-009",
    category: "protection",
    rule: "SD card power rail MUST be isolated from processor VCC (series resistor or load switch). Hot-insertion creates current surge that can brownout the processor.",
    reasoning: "SBI LCD boards: SD card socket shared VCC rail directly with processor. Card power-up inrush pulled VCC below brownout threshold, causing processor reset and boot loop. Different card brands caused different severity. Standardize on known-good card models for production (Toshiba 8GB worked, Kingston 8GB locked LCD).",
    sourceProject: "SBI Pellet Stove Controllers",
    severity: "should",
    status: "approved",
    addedDate: "2026-03-02",
  },
  {
    id: "rel-019",
    category: "reliability",
    rule: "Safety thresholds (pressure kill points, overtemp limits) must NEVER equal or be close to control setpoints. Leave adequate margin between detection thresholds and operating ranges.",
    reasoning: "SBI Osburn 3000: KIP (Kill Input Pressure) default of 0.100 inH2O conflicted with heat levels targeting 0.100 inH2O pressure. Wind gusts at low heat levels dropped pressure below KIP, triggering nuisance shutdowns. Increased pressure_error_delay from 3 to 10 seconds and separated detection criteria for low vs high speed operation.",
    sourceProject: "SBI Osburn 3000 / Multi-product",
    severity: "must",
    status: "approved",
    addedDate: "2026-03-02",
  },
  {
    id: "rel-020",
    category: "reliability",
    rule: "When substituting processors in the same family (even pin-compatible parts), always recompile AND validate firmware. Same pinout does NOT guarantee same execution behavior. Auto-update systems must check processor compatibility to prevent bricking.",
    reasoning: "SBI PIC18F26K22 → PIC18F24K22 substitution during chip shortage: POWER116.ROM caused continuous reboot loop on the 24K22. Since board was constantly rebooting, bootloader couldn't receive recovery commands. Required 5 separate safeguards: separate firmware, version spoofing, different bootloader command, version subcode, visual board distinction.",
    applies: ["PIC18F26K22", "PIC18F24K22"],
    sourceProject: "SBI Pellet Stove Controllers",
    severity: "must",
    status: "approved",
    addedDate: "2026-03-02",
  },
  {
    id: "mfg-001",
    category: "manufacturing",
    rule: "Add fiducial marks (circular plated SMT pads ~0.1 inch diameter) for pick-and-place optical alignment. Minimum 2 per panel, as far apart as possible. At least one board edge must be > 3.75 inches for SMT machine processing.",
    reasoning: "DFM review of SBI third-party board design revealed missing fiducials and undersized board dimension. Boards smaller than 3.75 inches on all edges need breakaway edges or tab-routed panels for SMT processing. REC uses no-clean reflow process — avoids aqueous wash.",
    sourceProject: "SBI DFM Review (free-group-chat)",
    severity: "must",
    status: "approved",
    addedDate: "2026-03-02",
  },
  {
    id: "mfg-002",
    category: "manufacturing",
    rule: "Prefer 0805 package for SMT resistors and capacitors (REC standard stock). Crystal load capacitors must be placed close to BOTH crystal AND processor. Route so no supply current for other ICs flows through decoupling caps.",
    reasoning: "DFM review: 0603 and 0402 available but less common at REC. Avoid 1812 ceramic caps and HC49 crystals when all other components are small. Crystal lines should not run from one side of CPU to the other. Each decoupling cap serves as a dedicated power supply for its IC.",
    sourceProject: "SBI DFM Review (free-group-chat)",
    severity: "should",
    status: "approved",
    addedDate: "2026-03-02",
  },

  // ── Roanoke Controls Internal Design Rules (from roanokecontrols Slack archive 2015-2025) ──

  {
    id: "mfg-003",
    category: "manufacturing",
    rule: "QFN paste mask MUST use home plate (pentagonal) apertures on corner pads and window-pane pattern on center ground pad at 50-60% coverage. Standard rectangular apertures cause 30%+ rotation and solder ball defects.",
    reasoning: "Nidek medical BMS first production batch had 30% QFN rotation rate. QFN packages lack leads for self-centering — unequal solder surface tension from standard apertures rotates the part. Home plate apertures create inward-biased forces. Oversized center pad apertures cause solder balls that escape under the package and short to adjacent pads.",
    sourceProject: "REC Nidek Medical / Quality",
    severity: "must",
    status: "approved",
    addedDate: "2026-03-02",
  },
  {
    id: "mfg-004",
    category: "manufacturing",
    rule: "Verify component orientation in tape after loading EVERY new Digi-Reel order, even for repeat part numbers. Use pick-and-place camera to inspect first placement.",
    reasoning: "Digi-Reel cut tape orientation (component polarity vs sprocket holes) is inconsistent between orders. Entire production run had electrolytic capacitors placed 180° reversed because tape orientation differed from previous order of same part number. Full reels from manufacturer are consistent; Digi-Reel orders are not.",
    sourceProject: "REC Production / Quality",
    severity: "must",
    status: "approved",
    addedDate: "2026-03-02",
  },
  {
    id: "mfg-005",
    category: "manufacturing",
    rule: "Reflow oven MUST be dedicated to either leaded or lead-free solder. If sharing is unavoidable, run minimum 5 blank board passes at lead-free temperature before switching from leaded to lead-free.",
    reasoning: "Leaded flux (tac-flux) residue contaminates oven atmosphere, conveyor, and heating elements. Subsequent lead-free boards (SAC305) show increased solder defects from contamination. Even trace amounts of lead in SAC305 joints dramatically reduce fatigue life. REC quality investigation traced defect spike directly to timeline of leaded runs.",
    sourceProject: "REC Quality Department",
    severity: "must",
    status: "approved",
    addedDate: "2026-03-02",
  },
  {
    id: "sig-008",
    category: "signal-integrity",
    rule: "4-layer PCB stackup is MANDATORY for any WiFi design (ESP8266, ESP32, nRF). Inner layers provide power and ground planes essential for RF reference. 2-layer PCBs will have unreliable WiFi.",
    reasoning: "Bare ESP8266 QFN32 designs on 2-layer boards had malformed WiFi packets from inadequate ground plane. Inner layers serve as RF reference for antenna matching network. Antenna matching is extremely sensitive to ground plane quality. Module-based designs (ESP32-WROVER) partially mitigate this with integrated shielding but still benefit from 4-layer PCB.",
    applies: ["ESP8266", "ESP32-WROVER", "nRF51822"],
    sourceProject: "REC ESP8266/ESP32 Research",
    severity: "must",
    status: "approved",
    addedDate: "2026-03-02",
  },
  {
    id: "sig-009",
    category: "signal-integrity",
    rule: "On ESP32, verify VSPI vs HSPI bus selection before PCB layout. One SPI bus is used by onboard flash. Default VSPI: SCLK=18, MISO=19, MOSI=23, SS=5. Default HSPI: SCLK=14, MISO=12, MOSI=13, SS=15.",
    reasoning: "ESP32 SPI described as 'fraught with peril' due to VSPI/HSPI confusion and flash chip already connected to one bus. Using the wrong bus causes conflicts with flash operations. Pin remapping is possible but must be explicitly configured in software.",
    applies: ["ESP32-WROVER"],
    sourceProject: "REC ESP32 Research (esp32_research)",
    severity: "must",
    status: "approved",
    addedDate: "2026-03-02",
  },
  {
    id: "comp-001",
    category: "component-selection",
    rule: "ESP8266 designs MUST use 26MHz crystal. 24MHz crystal causes complete WiFi failure — device reports connection but sends malformed packets rejected by all receivers.",
    reasoning: "REC bare ESP8266 design used 24MHz crystal. ESP8266 RF synthesizer PLL generates incorrect carrier frequencies with wrong reference. Device's own MAC layer reports success because it doesn't check RF accuracy. Hard requirement, not adjustable in firmware.",
    applies: ["ESP8266"],
    sourceProject: "REC ESP8266 Research",
    severity: "must",
    status: "approved",
    addedDate: "2026-03-02",
  },
  {
    id: "comp-002",
    category: "component-selection",
    rule: "For medical devices, use pre-certified power supply bricks (IEC 60601-1) rather than custom on-board supplies unless volume exceeds 10,000+ units/year. Per-unit premium ($3-6) is trivial vs certification costs ($50K+).",
    reasoning: "Nidek medical BMS: custom 3V3 supply at $3/unit required $50K+ IEC 60601 testing. Pre-certified medical brick at $6/unit eliminated all power supply safety testing. Certification transfers as recognized component. CUI, Mean Well Medical, TDK-Lambda all offer certified modules.",
    sourceProject: "REC Nidek Medical",
    severity: "should",
    status: "approved",
    addedDate: "2026-03-02",
  },
  {
    id: "rel-021",
    category: "reliability",
    rule: "In IoT devices with safety-critical outputs, use dual-processor architecture: communications processor (ESP32) makes 'suggestions,' dedicated safety processor (PIC24) controls all outputs. Safety processor defaults to safe state if communications processor crashes.",
    reasoning: "Pitts & Spitts All-In-One grill controller: ESP32 core panics from WiFi stack would have left ignitor and auger in dangerous states if ESP32 had direct output control. PIC24 independently validates all commands. If ESP32 crashes, PIC24 defaults to outputs off. WiFi/BLE stacks are inherently unreliable — never trust them with safety-critical I/O.",
    applies: ["ESP32-WROVER", "PIC24FJ"],
    sourceProject: "REC Pitts & Spitts All-In-One Controller",
    severity: "must",
    status: "approved",
    addedDate: "2026-03-02",
  },
  {
    id: "rel-022",
    category: "reliability",
    rule: "Any change in motor (fan, auger, pump) RPM, CFM, or airflow path requires complete PID re-tuning. Never ship a motor change without full re-characterization over 18+ hours of data collection.",
    reasoning: "Kuma Stoves changed from 1 RPM to 2 RPM auger and new fan simultaneously. All previous PID tuning was invalid. Maximum auger duty halved but grill ran poorly. New fan ramped up slower, moved less air. PID parameters are tuned to a specific plant model — changing actuators changes the plant transfer function.",
    sourceProject: "REC Kuma Stoves / Madera",
    severity: "must",
    status: "approved",
    addedDate: "2026-03-02",
  },
  {
    id: "prot-010",
    category: "protection",
    rule: "AC ignitors (silicon nitride hot rod elements) MUST be electrically isolated from grounded enclosures. Leakage current through hot ceramic insulator trips GFCI at as low as 5mA, even when ignitor is not actively energized.",
    reasoning: "Hundreds of GFCI tripping complaints across multiple pellet grill customers (Pitts & Spitts, Dalsin). Ignitor shell contacts grill frame. When hot, ceramic breakdown allows leakage to ground. Physical distances change as ignitor heats up. Duty-cycling at 50-70% reduces trips. Better-quality ignitors (Surface Igniter LLC) eliminated the issue.",
    sourceProject: "REC Pellet Grill Controllers",
    severity: "must",
    status: "approved",
    addedDate: "2026-03-02",
  },
  {
    id: "prot-011",
    category: "protection",
    rule: "Fusible resistor rating MUST be sized to protect downstream components, NOT to survive surges. Replacing a blowing fusible resistor with a higher-wattage version defeats the protection and damages downstream circuits.",
    reasoning: "Southbend oven: field technicians replaced fusible resistors with higher-wattage versions to stop nuisance blowing. Subsequently, MOV and circuit board traces were destroyed by surges the fusible resistor was meant to absorb. The fusible resistor IS the protection device — it's supposed to blow. Place MOVs downstream of fusible resistors.",
    sourceProject: "REC Southbend Oven Controllers",
    severity: "must",
    status: "approved",
    addedDate: "2026-03-02",
  },
  {
    id: "emc-008",
    category: "emc",
    rule: "WiFi/BLE antenna MUST NOT contact metal enclosure. Use insulating collar/grommet for external RP-SMA antennas. For production: prefer PCB trace antenna inside plastic enclosure extending beyond metal housing.",
    reasoning: "Nearly every WiFi signal complaint in grill products traced to antenna threading grounding to metal hopper body. Signal drops from -28 dBm to below -70 dBm. Users mount antenna through metal without insulation. PCB trace antenna saves $0.75/unit and eliminates the issue. Plastic enclosure section must extend beyond metal body for radiation.",
    sourceProject: "REC WiFi Grill Controllers",
    severity: "must",
    status: "approved",
    addedDate: "2026-03-02",
  },
  {
    id: "test-006",
    category: "testability",
    rule: "PIC code protection alone is insufficient for firmware IP protection. Use multi-layer strategy: bootloader-only pre-programming, application loaded stateside, unique product ID per customer, copyright string embedding, and secure boot on newer MCUs.",
    reasoning: "RecTec Grills cloned REC's PIC18 firmware byte-for-byte including copyright notice. Chinese manufacturer copied a control board completely when boards were sent overseas for assembly. PIC code protection reads as zeros but is trivially bypassable. Sending complete boards overseas gives manufacturers working hardware to reverse-engineer.",
    applies: ["PIC18F26K22"],
    sourceProject: "REC Internal Engineering",
    severity: "should",
    status: "approved",
    addedDate: "2026-03-02",
  },
  {
    id: "comp-003",
    category: "component-selection",
    rule: "For switch contacts carrying less than 100mA, specify gold-plated contacts. Standard tin or silver contacts develop oxide films that increase contact resistance until signal is lost.",
    reasoning: "Race car data acquisition switches (Mike Pearl) became intermittent after 6-12 months. At signal-level currents (<100mA), insufficient energy to break through surface oxide on tin/silver contacts. Higher-current switching (>1A) creates micro-arcs that self-clean. Look for 'signal level' or 'logic level' rated switches in datasheets.",
    sourceProject: "REC Mike Pearl Racing Electronics",
    severity: "should",
    status: "approved",
    addedDate: "2026-03-02",
  },
  {
    id: "comp-004",
    category: "component-selection",
    rule: "When substituting MOSFETs, verify Vgs(th) and switching characteristics at ACTUAL gate drive voltage. Two MOSFETs with identical voltage/current ratings can have completely different switching behavior.",
    reasoning: "IRL540 substituted for IRL530 in pinball solenoid drivers (Rottendog) caused intermittent misfiring. IRL540 Vgs(th) ~2.0V vs IRL530 ~1.0V. With slow gate drive, higher threshold caused late turn-on. This is NOT a bidirectional substitution despite similar datasheets.",
    applies: ["IRL540", "IRL530"],
    sourceProject: "REC Rottendog Pinball",
    severity: "must",
    status: "approved",
    addedDate: "2026-03-02",
  },
];
