import { DesignRule } from "../types/index.js";

// ── Your team's design rules and conventions ──
// These get checked automatically when planning schematics
// and flagged in the check-design-rules tool.

export const designRules: DesignRule[] = [
  // ── Power Integrity ──
  {
    id: "pwr-001",
    category: "power-integrity",
    rule: "Every IC VDD pin gets a 100nF X7R ceramic within 3mm and a 10uF bulk within 10mm",
    reasoning: "Standard decoupling practice. Y5V ceramics lose too much capacitance at operating voltage.",
    severity: "must",
    status: "approved",
    addedDate: "2026-02-28",
  },
  {
    id: "pwr-002",
    category: "power-integrity",
    rule: "Power trace width minimum 20mil for signals under 500mA, 40mil for up to 1A",
    reasoning: "Based on 1oz copper, 10°C rise. Our standard stack-up.",
    severity: "must",
    status: "approved",
    addedDate: "2026-02-28",
  },

  // ── Component Selection ──
  {
    id: "comp-001",
    category: "component-selection",
    rule: "0402 resistors: max 50mW dissipation in production designs, use 0603 for anything above",
    reasoning: "Our reflow profile on line 2 runs at upper end of spec. 0402 at full rated power showed 3% field return rate on PROJ-2024-017.",
    severity: "must",
    applies: ["resistor"],
    exceptions: "Pull-ups and pull-downs exempt — negligible power dissipation",
    sourceProject: "PROJ-2024-017",
    status: "approved",
    addedDate: "2026-02-28",
  },
  {
    id: "comp-002",
    category: "component-selection",
    rule: "Prefer inventory-abundant parts over exact-match spec when both meet requirements",
    reasoning: "Reduces cost, avoids procurement delays, keeps feeders loaded",
    severity: "should",
    status: "approved",
    addedDate: "2026-02-28",
  },

  // ── Layout ──
  {
    id: "lay-001",
    category: "layout",
    rule: "ESP32 antenna keep-out: 15mm ground-plane clearance, stitching vias every 2mm at boundary",
    reasoning: "Per Espressif hardware design guide. Violating this degrades WiFi by 6-10dBm.",
    applies: ["ESP32-S3", "ESP32-C3", "ESP32-C6", "ESP32-S2"],
    severity: "must",
    status: "approved",
    addedDate: "2026-02-28",
  },

  // ── EMC ──
  {
    id: "emc-001",
    category: "emc",
    rule: "All external connectors must have ESD protection on signal lines",
    reasoning: "Required for CE/FCC certification. Failed on PROJ-2023-011 without it.",
    severity: "must",
    sourceProject: "PROJ-2023-011",
    status: "approved",
    addedDate: "2026-02-28",
  },

  // ── Manufacturing ──
  {
    id: "mfg-001",
    category: "manufacturing",
    rule: "Minimum 3 fiducials per board — 2 global + 1 local near fine-pitch components",
    reasoning: "Our pick-and-place requires 2 global fiducials minimum. Third local fiducial improves placement accuracy for QFN/BGA.",
    severity: "must",
    status: "approved",
    addedDate: "2026-02-28",
  },
  {
    id: "mfg-002",
    category: "manufacturing",
    rule: "Test points on all power rails and critical signals — 1mm pad minimum",
    reasoning: "Required for bed-of-nails testing on our ICT fixture",
    severity: "should",
    status: "approved",
    addedDate: "2026-02-28",
  },

  // ── Carter-Hoffmann M-Series Rules (from Slack archive 2020-2025) ──

  {
    id: "sig-001",
    category: "signal-integrity",
    rule: "Digital communication over cables MUST use shielded twisted pair (CAT-5e/RJ45). Never use flat telco (RJ11) for shift register clock/data signals.",
    reasoning: "Years of intermittent flicker and signal integrity failures across entire M-Series product line traced to unshielded flat telco cables. RJ11 cables have no shielding, no twisted pairs, inconsistent manufacturing quality, and wildly variable capacitance between manufacturers and batches.",
    sourceProject: "Carter-Hoffmann M-Series",
    severity: "must",
    status: "approved",
    addedDate: "2026-02-28",
  },
  {
    id: "sig-002",
    category: "signal-integrity",
    rule: "Route digital signal cables AWAY from AC voltage sources. Maintain minimum 50mm separation. Use ferrite coils on signal wires near power entry.",
    reasoning: "AC muffin fan (208V) EMI coupled into DC supply through adjacent cable routing, causing false switching and voltage spikes that destroyed display board ICs at Popeyes field installation.",
    sourceProject: "Carter-Hoffmann Popeyes Field Failure",
    severity: "must",
    status: "approved",
    addedDate: "2026-02-28",
  },
  {
    id: "mfg-003",
    category: "manufacturing",
    rule: "When specifying connectors for production cables, name exact manufacturer and part number. Document crimping procedure including insulation strip length (~1/4\"), strain relief engagement, and connector alignment.",
    reasoning: "Cable quality variations caused years of field failures. Outer insulation stripped too far back, strain relief not engaged, connector alignment off — all contributed to intermittent communication failures on shift register lines.",
    applies: ["RJ11", "RJ45", "JST-PH"],
    sourceProject: "Carter-Hoffmann M-Series (rma_flicker)",
    severity: "must",
    status: "approved",
    addedDate: "2026-02-28",
  },
  {
    id: "mfg-004",
    category: "manufacturing",
    rule: "Power supply boards MUST be tested at actual worst-case load for the intended application, not just nominal. For dual-transformer variants, test at double the single-transformer load.",
    reasoning: "FGLF0604-01 PSU boards failed after 30-60 min in M343 passthrough cabinets because dual-transformer load was nearly double what single-transformer test procedure covered.",
    sourceProject: "Carter-Hoffmann M343",
    severity: "must",
    status: "approved",
    addedDate: "2026-02-28",
  },
  {
    id: "rel-001",
    category: "reliability",
    rule: "Plan bootloader flash size for maximum expected future needs from the start. Reserve at least 2x the initial bootloader size.",
    reasoning: "Increasing bootloader from 19KB to 24KB for ConnectWare support shifted the application start address, making firmware images incompatible. Required separate part numbers (FGLF0605-01 vs -02) and version numbering schemes.",
    sourceProject: "Carter-Hoffmann ConnectWare Integration",
    severity: "should",
    status: "approved",
    addedDate: "2026-02-28",
  },
  {
    id: "rel-002",
    category: "reliability",
    rule: "When removing a state from a firmware state machine, grep the ENTIRE codebase for every reference — transitions into, out of, and guards checking for that state. Remove ALL of them.",
    reasoning: "Removing PROGRAM_ADJUST mode without cleaning all references caused display freeze when buttons were pressed during NOT_AT_SETPOINT state. The state machine transitioned to a state that no longer existed.",
    sourceProject: "Carter-Hoffmann WAWA v3.03",
    severity: "must",
    status: "approved",
    addedDate: "2026-02-28",
  },
  {
    id: "comp-003",
    category: "component-selection",
    rule: "When substituting logic IC speed grades (e.g., HC vs HCS series), full regression testing across ALL board configurations is mandatory. Faster is not always better.",
    reasoning: "Swapping HC08 AND gates to faster HCS08 fixed display flicker but broke button detection on downstream single-window displays. Required stocking two variants depending on configuration.",
    applies: ["HC08", "HCS08"],
    sourceProject: "Carter-Hoffmann M-Series (rma_flicker)",
    severity: "must",
    status: "approved",
    addedDate: "2026-02-28",
  },
  {
    id: "comp-004",
    category: "component-selection",
    rule: "Set NTC thermistor short-detection threshold to 500 ohm (not 1000 ohm) to avoid false errors in cold environments. 1000 ohm corresponds to ~32°F which is a realistic startup temperature.",
    reasoning: "Units on loading docks and unheated kitchens threw false short errors on startup with 1000 ohm threshold. Changed to 500 ohm in firmware v3, allowing minimum temperature reading down to -125°C.",
    applies: ["NTC-thermistor"],
    sourceProject: "Carter-Hoffmann NTX Cook-and-Hold",
    severity: "should",
    status: "approved",
    addedDate: "2026-02-28",
  },
  {
    id: "comp-005",
    category: "component-selection",
    rule: "Derate TRIACs to 5A maximum in production despite higher datasheet ratings. Heatsink required for continuous-duty heater outputs.",
    reasoning: "BTA12-600BWRG and T1235-600G-TR both rated 12A but production boards use 5A max. Higher current requires better thermal management than typical PCB mounting provides.",
    applies: ["BTA12-600BWRG", "T1235-600G-TR"],
    sourceProject: "Carter-Hoffmann M-Series",
    severity: "must",
    status: "approved",
    addedDate: "2026-02-28",
  },
];
