export { referenceCircuits } from "./reference-circuits.js";
export { inventory } from "./inventory.js";
export { powerSupplies } from "./power-supplies.js";
export { protectionCircuits } from "./protection-circuits.js";
export { designRules } from "./design-rules.js";
export { lessonsLearned } from "./lessons-learned.js";
export { componentNotes } from "./component-notes.js";
export { substitutionRules } from "./substitution-rules.js";
export { dfmRules } from "./dfm-rules.js";
export { deratingRules } from "./derating-rules.js";
export { vendorPreferences } from "./vendor-preferences.js";
export { REC_LIBRARY_NAME, footprintSizeMap, supplySymbols, keyParts } from "./eagle-libraries.js";

// ── Mined Design Knowledge ──
export { minedDecoupling } from "./mined-decoupling.js";
export { minedPowerSupplies, triacCircuits, emcComponents, fuseRatings } from "./mined-power-supplies.js";
export { mcuProfiles, mcuFamilySummary } from "./mined-mcus.js";
export { minedPullups } from "./mined-pullups.js";
export { minedRouting } from "./mined-routing.js";
export { minedPlacement } from "./mined-placement.js";
export { minedSilkscreen } from "./mined-silkscreen.js";
export { picAdDesigns, picAdSummary, analogSourceTypes, pinFunctionDistribution } from "./mined-pic-ad.js";
export { triacDesigns, triacModels, optoModels, snubberCapValues, gateResistorValues, mcuDriveParts } from "./mined-triacs.js";
export { displayDesigns, displayTypes, displayDriverTypes, displayInterfaceTypes } from "./mined-displays.js";
export { powerCapacityBoards, powerCapacitySummary } from "./mined-power-capacity.js";
export { relayDesigns, relayTypes, relayDriverICs, relayCoilVoltages } from "./mined-relays.js";
export { commInterfaceDesigns, commInterfaceTypes, commTransceiverParts } from "./mined-comm-interfaces.js";
export { sensorDesigns, sensorTypes, conditioningComponents } from "./mined-sensors.js";
export { ledDesigns, ledColorDistribution, ledCurrentLimitingResistors } from "./mined-leds.js";
export { protectionDesigns, protectionTypes, tvsToConnectorDistance } from "./mined-protection.js";
export { testPointDesigns, testPointCategories, debugHeaders } from "./mined-testpoints.js";
export { boardSummaries, boardSummarySummary } from "./mined-board-summary.js";
export { programmingInterfaces } from "./mined-programming.js";
