import { LessonLearned } from "../types/index.js";

// ── Hard-won knowledge from real projects ──
// This is the most valuable file in the server.
// Every entry here prevents a future engineer from repeating a mistake.

export const lessonsLearned: LessonLearned[] = [
  {
    id: "ll-001",
    title: "ESP32 WiFi drops with distant decoupling",
    category: "design-error",
    description: "WiFi TX power drops and connection instability when bulk decoupling cap is too far from VDD pins",
    whatHappened: "Asset tracker rev A had intermittent WiFi disconnects under load. Signal strength measured 8dBm below expected.",
    rootCause: "10uF bulk capacitor was placed 25mm from ESP32 VDD3P3 pins due to layout constraints. High-frequency switching noise on the 3.3V rail during WiFi TX.",
    fix: "Moved 10uF bulk cap within 10mm of VDD pins. Added second 100nF directly at VDD3P3_RTC pin. Rev B fixed the issue completely.",
    affectedComponents: ["ESP32-S3-WROOM-1"],
    affectedCircuits: ["esp32-s3-base"],
    sourceProject: "PROJ-2024-017 Asset Tracker",
    severity: "major",
    status: "approved",
    addedDate: "2026-02-28",
  },

  // ── Carter-Hoffmann M-Series Lessons (from Slack archive 2020-2025) ──

  {
    id: "ll-002",
    title: "Telco cable quality causes intermittent display flicker",
    category: "manufacturing",
    description: "6-pin telco (RJ11) cable quality caused years of intermittent display flicker on M-Series holding cabinets",
    whatHappened: "Alphanumeric display boards flickered intermittently, especially in passthrough cabinets (M343) with master+slave configurations. Problem appeared random and was extremely difficult to reproduce consistently.",
    rootCause: "Cable manufacturing defects: outer insulation stripped too far back (~1/2\" instead of ~1/4\"), strain relief not engaged during crimping, connector alignment off causing deformed plastic in contact channels. Added capacitance from poor cables created crosstalk on shift register clock/data lines.",
    fix: "1) Specified Assmann WSW A-MO-6-6-F50 plugs with proper crimping procedure. 2) Wire spec: 26AWG with proper insulation thickness, strain relief MUST be engaged. 3) Changed HC08 AND gate ICs to faster HCS08 across all display boards (FGLF0598-03→05, FGLF0599-03→05, FGLF0626-00→01, FGLF0627-00→01). Tony tested 252 combinations (7 boards, 36 cables, 9 plug types) to prove root cause.",
    affectedComponents: ["HC08", "HCS08", "RJ11"],
    affectedCircuits: ["m-series-display"],
    sourceProject: "Carter-Hoffmann M-Series (rma_flicker)",
    severity: "critical",
    status: "approved",
    addedDate: "2026-02-28",
  },
  {
    id: "ll-003",
    title: "Faster logic IC fix introduced new button detection bug",
    category: "component-issue",
    description: "Swapping to faster AND gate ICs fixed display flicker but broke button responsiveness on downstream single-window displays",
    whatHappened: "After changing HC08 AND gates to faster HCS08 to fix flicker, timer buttons on single-window displays became unresponsive when daisy-chained downstream of dual-window master boards.",
    rootCause: "The faster HCS08 propagation delay changed the timing relationship between shift register clock and data lines. Single-window displays downstream of dual-window masters saw different timing margins than the original HC08 design was tuned for.",
    fix: "Required stocking two different driver IC variants — HCS08 for boards that don't chain to single-window displays, and HC08 + trace jumper for boards that do. Full regression testing across ALL board configurations is mandatory for any logic IC substitution.",
    affectedComponents: ["HC08", "HCS08"],
    affectedCircuits: ["m-series-display"],
    sourceProject: "Carter-Hoffmann M-Series (rma_flicker)",
    severity: "major",
    status: "approved",
    addedDate: "2026-02-28",
  },
  {
    id: "ll-004",
    title: "Power supply failures at full load in passthrough cabinets",
    category: "field-failure",
    description: "FGLF0604-01 power supply boards failing after 30-60 minutes under full load",
    whatHappened: "PSU boards in M343 passthrough cabinets (worst-case: 15 heaters, controls on both front and back) showed black marks near X3 and failed after 30 min to 1 hour. Failure rate escalated from 1-2 units to multiple per batch of 30.",
    rootCause: "Dual transformer power supply variant was being tested with single-transformer load levels. Actual load in M343 passthrough is nearly double what was tested.",
    fix: "Double test load for dual-transformer variant. Extended full-load test procedure: use test firmware to light every display segment, run maximum boards for 1+ hour. Measure DC current on red wire from PSU to breakout board.",
    affectedComponents: ["FGLF0604-01"],
    affectedCircuits: ["m-series-psu"],
    sourceProject: "Carter-Hoffmann M343",
    severity: "critical",
    status: "approved",
    addedDate: "2026-02-28",
  },
  {
    id: "ll-005",
    title: "EMI from AC fan motor caused overvoltage board damage",
    category: "field-failure",
    description: "Display boards at Popeyes location found charred with ICs violently decapped from overvoltage",
    whatHappened: "Multiple display boards destroyed — low-voltage ICs showed signs of catastrophic overvoltage. No visible damage to power supply or controller board.",
    rootCause: "AC muffin fan (208V) with motor start capacitor was mounted adjacent to power supply. Fan power cord was laying directly on the PSU wire harness. EMI from fan motor likely coupled into the DC supply, causing false switching and voltage spikes. Telco signal cables routed too close to AC power lines amplified the problem.",
    fix: "1) Route display/signal cables AWAY from AC voltage sources. 2) Use ferrite coils on signal wires near power entry. 3) Consider shielded cables for signal runs near AC. 4) Use nylon standoff nuts instead of metal keps nuts to reduce ground loop paths. 5) Add dielectric sleeving where signal and power wires must cross.",
    affectedComponents: ["FGLF0598", "FGLF0599"],
    sourceProject: "Carter-Hoffmann Popeyes Field Failure",
    severity: "critical",
    status: "approved",
    addedDate: "2026-02-28",
  },
  {
    id: "ll-006",
    title: "USB drive compatibility varies widely with embedded USB host",
    category: "component-issue",
    description: "Not all USB drives work with PIC-based embedded USB host controller",
    whatHappened: "Specific USB drives failed to be recognized by USBHost Mux board for firmware loading. Some drives worked for one engineer but not another.",
    rootCause: "Embedded USB host stack on PIC has limited device compatibility. No full OS to provide driver abstraction for different USB flash controller chipsets. Different USB drive manufacturers use different internal controllers.",
    fix: "Qualify specific USB drive models and stick with them. Document known-good drive models. Do not guarantee compatibility with arbitrary drives. To truly support all hardware would require an OS on the embedded system.",
    affectedComponents: ["PIC-USB-Host"],
    sourceProject: "Carter-Hoffmann WAWA (usb-host)",
    severity: "minor",
    status: "approved",
    addedDate: "2026-02-28",
  },
  {
    id: "ll-007",
    title: "Bootloader size change makes firmware images incompatible",
    category: "design-error",
    description: "Increasing bootloader from 19KB to 24KB for ConnectWare support created incompatible firmware images",
    whatHappened: "Adding PowerHouse Dynamics ConnectWare support required a larger bootloader (24KB vs original 19KB). Firmware built for one bootloader size would not work with the other.",
    rootCause: "The 5KB size difference shifts the application start address. Firmware images are not self-describing — they assume a fixed bootloader size. Old firmware flashed onto a board with the new bootloader writes to the wrong addresses.",
    fix: "Created two separate part numbers: FGLF0605-01 (standard, 19KB bootloader) and FGLF0605-02 (ConnectWare, 24KB bootloader). Firmware versions for new bootloader start at 4.xx to make version incompatibility obvious. Plan bootloader size for maximum expected future needs from the start.",
    affectedComponents: ["PIC-bootloader"],
    sourceProject: "Carter-Hoffmann ConnectWare Integration",
    severity: "major",
    status: "approved",
    addedDate: "2026-02-28",
  },
  {
    id: "ll-008",
    title: "Shift register comms over telco cables should use shielded twisted pair",
    category: "design-error",
    description: "6-pin telco cables are fundamentally unreliable for cascaded digital communication",
    whatHappened: "Years of intermittent failures, flicker, and signal integrity issues across the entire M-Series product line traced back to using unshielded flat telco cables for shift register clock/data signals.",
    rootCause: "RJ11 telco cables are designed for analog voice, not digital data. No shielding, no twisted pairs, inconsistent manufacturing quality, poor retention force. Cable capacitance varies wildly between manufacturers and even between batches.",
    fix: "For any new design with cascaded digital communication: use 8-pin CAT-5e/Ethernet connectors with shielded twisted pairs. Standard ethernet cables are manufactured in volume on precise equipment that eliminates crimping variation. RJ45 jacks have better retention than RJ11. Budget the extra connector cost — it's far cheaper than years of field failures.",
    affectedCircuits: ["m-series-display", "m-series-comms"],
    sourceProject: "Carter-Hoffmann M-Series (all channels)",
    severity: "critical",
    status: "approved",
    addedDate: "2026-02-28",
  },
  {
    id: "ll-009",
    title: "NTC sensor short detection threshold too aggressive for cold environments",
    category: "design-error",
    description: "Temperature sensor short detection flagging false errors in cold startup conditions",
    whatHappened: "NTX Cook-and-Hold software v2 flagged anything under 1000 ohm as a shorted temperature sensor, which corresponds to about 32°F. Units in cold environments (loading docks, unheated kitchens) threw false short errors on startup.",
    rootCause: "Short detection threshold was set too close to the low end of normal operating range. 1000 ohm on an NTC thermistor corresponds to approximately 32°F — a temperature that equipment could realistically encounter.",
    fix: "Changed short detection threshold from 1000 ohm to 500 ohm in firmware v3. This allows minimum temperature reading down to -125°C before reporting a short. Lowest displayed temperature is 1°F. Trade-off: less accurate detection of actual shorts below freezing, but prevents false errors in realistic cold environments.",
    affectedComponents: ["NTC-thermistor"],
    sourceProject: "Carter-Hoffmann NTX Cook-and-Hold",
    severity: "major",
    status: "approved",
    addedDate: "2026-02-28",
  },
  {
    id: "ll-010",
    title: "Removing firmware state without full cleanup causes undefined behavior",
    category: "design-error",
    description: "Removing PROGRAM_ADJUST mode from firmware without cleaning all references caused display freeze",
    whatHappened: "After removing PROGRAM_ADJUST mode to fix timer button delay, pressing up/down arrows during NOT_AT_SETPOINT (warmup) state caused the drawer display to enter an undefined state with no exit — complete display freeze.",
    rootCause: "References to the removed PROGRAM_ADJUST mode were not completely cleaned up from the NOT_AT_SETPOINT state handler. The state machine transitioned to a state that no longer existed.",
    fix: "Eliminated ALL remaining PROGRAM_ADJUST mode references across every state in the firmware (v3.03). When removing a state from a state machine, grep the entire codebase for every reference — transitions into, out of, and guards checking for that state.",
    sourceProject: "Carter-Hoffmann WAWA v3.03",
    severity: "major",
    status: "approved",
    addedDate: "2026-02-28",
  },

  // ── Devon-REC / Nidek Battery Pack Lessons (from Slack archive 2019-2025) ──

  {
    id: "ll-011",
    title: "BQ294700 floating inputs trigger fuse blow output",
    category: "design-error",
    description: "Battery overvoltage protection IC fires fuse blow output when cell sense inputs are floating",
    whatHappened: "During battery pack assembly, the BQ294700 had power before cells were connected through the dip switch. The fuse blow output latched active, potentially blowing the chemical fuse.",
    rootCause: "When BQ294700 cell monitoring inputs are floating but the IC is powered, input voltages float high enough to exceed the overvoltage threshold and trigger the fuse blow output. The original Devon BQ40Z50 design already had this solved — the monitor IC power was routed through the dip switch.",
    fix: "Route power supply for external monitor IC through the final cell connection switch so U2 only powers on after all cells are in place. For existing boards: open all dip switches, solder cells for B- through B3, close dip switches 1-4, THEN solder B4. Verify FUSE flag in BQStudio before closing fuse dip switch.",
    affectedComponents: ["BQ294700", "BQ294711"],
    sourceProject: "Devon-REC Nidek Battery Pack",
    severity: "critical",
    status: "approved",
    addedDate: "2026-02-28",
  },
  {
    id: "ll-012",
    title: "BQ fuel gauge chemistry must be programmed AFTER firmware",
    category: "design-error",
    description: "Programming firmware after chemistry overwrites the chemistry selection on TI BQ fuel gauges",
    whatHappened: "After programming the battery chemistry and then programming the firmware, the chemistry was overwritten. The voltage measurement changed and state of charge dropped instantly. Programming chemistry after firmware caused an ACLW flag disabling charging.",
    rootCause: "The .SREC firmware file includes the chemistry file, parameter settings, and lifetime data from when it was created. Loading firmware after chemistry overwrites the chemistry selection with whatever was baked into the SREC.",
    fix: "Correct golden file creation sequence: 1) Load firmware (.SREC), 2) Load chemistry file, 3) Change operational parameters, 4) Flush lifetime data (LT_FLUSH), 5) Clear lifetime (LT_RESET), 6) Clear permanent failures (PF_CLEAR), 7) Clear black box (BBR_CLEAR), 8) Reset BQ, 9) Save new SREC. Use this SREC for all production boards.",
    affectedComponents: ["BQ40Z60", "BQ40Z50"],
    sourceProject: "Devon-REC Nidek Battery Pack",
    severity: "major",
    status: "approved",
    addedDate: "2026-02-28",
  },
  {
    id: "ll-013",
    title: "Test fixture alligator clips cause false BMS protection faults",
    category: "manufacturing",
    description: "Alligator clip connections on BMS test fixture caused intermittent FUSE errors and false failures",
    whatHappened: "During production testing, 3 of first 7 packs failed with FUSE errors. One failed, then passed on retest. Overall yield was inconsistent and appeared random.",
    rootCause: "Alligator clips on the test fixture created intermittent contact resistance and momentary open circuits. When a cell connection briefly opened during testing, the BQ294700 saw a transient voltage spike and triggered the fuse output. Switching to soldered connections with inline switches resolved the issue.",
    fix: "Use permanent soldered connections with inline switches for BMS test fixtures — never alligator clips. After switching, yield went from ~60% to nearly 100%. Tony retested units that failed with clips using soldered connections and most passed.",
    affectedComponents: ["BQ294700", "BQ294711"],
    sourceProject: "Devon-REC Nidek Battery Pack",
    severity: "major",
    status: "approved",
    addedDate: "2026-02-28",
  },
  {
    id: "ll-014",
    title: "FET overheating during charge traced to BQ40Z60 IC, not the FETs",
    category: "component-issue",
    description: "One battery pack board showed 66°C FET temperatures during charging, root cause was the BQ40Z60 not the MOSFETs",
    whatHappened: "Unit marked #13 had FETs reaching 66°C within 5 minutes of charging at 1.7A. Historical data showed max FET temp of 84°C. Replacing both high-side and low-side FETs with new US-sourced parts did not resolve the overheating.",
    rootCause: "The BQ40Z60 itself was generating excessive heat — it was as hot as the FETs. At 1MHz synchronous buck switching frequency, a marginal BQ40Z60 IC caused excessive switching losses. Replacing both FETs confirmed they were not the problem. Reducing charge voltage to 4.1V per cell allowed slower but functional charging.",
    fix: "When diagnosing FET overheating in BMS designs, check the fuel gauge IC temperature as well — it drives the gate signals. Replace the BQ IC, not just the FETs. Consider that 1MHz switching frequency creates significant losses. Monitor internal temperature sensor in BQStudio.",
    affectedComponents: ["BQ40Z60", "SIR158", "CSD17307"],
    sourceProject: "Devon-REC Nidek Battery Pack",
    severity: "major",
    status: "approved",
    addedDate: "2026-02-28",
  },
  {
    id: "ll-015",
    title: "Sudden load application triggers BMS short circuit protection",
    category: "design-error",
    description: "Instantaneous application of 5A discharge load triggers short circuit detection despite being within rated current",
    whatHappened: "Tail lamp test load (~5A) caused short circuit protection to trip on packs that worked fine with an O2 concentrator load (~3.2A) that ramps gradually. Energy Assurance test house saw high failure rates applying immediate 5A loads.",
    rootCause: "AFE short circuit protection threshold (ASCD1) was set for 44.4mV across the 5mΩ sense resistor (8.88A trip point) with 0μs delay. The inrush current from an incandescent lamp or sudden resistive load exceeds 8.88A momentarily even though steady-state current is only 5A. The Kingon reference pack exhibited the same behavior.",
    fix: "1) Test house must ramp discharge loads to 5A over ~5 seconds, not instantaneous. 2) Set charger input voltage to fixed 18.3V, not 19.3V. 3) Consider increasing ASCD delay from 0μs or raising threshold. 4) Document that even the reference pack fails the lamp test — this is expected behavior with the current protection settings.",
    affectedComponents: ["BQ40Z60", "BQ40Z50"],
    sourceProject: "Devon-REC Nidek Battery Pack",
    severity: "major",
    status: "approved",
    addedDate: "2026-02-28",
  },
  {
    id: "ll-016",
    title: "1MHz buck charger EMI requires snubber and shielding for medical certification",
    category: "emc",
    description: "BQ24610-based battery charger failed EMC pre-scan at 133MHz, requiring multiple mitigation strategies",
    whatHappened: "Battery pack failed CISPR11 Class B Group 1 radiated emissions limit by over 28dB at ~133MHz during charging. Near-field measurements showed -22.5dBm peak on existing pack vs -31dBm on BQ24610 eval board. 5dB improvement from component changes didn't help in lab testing.",
    rootCause: "1MHz synchronous buck converter switching transients radiate from the inductor and high-current loops. Switching rise/fall times remain the same regardless of charge current — reducing charge current doesn't help EMI. The primary noise source is the high-frequency current loop between input cap, FETs, and inductor.",
    fix: "Multi-pronged approach needed: 1) Add RC snubber on charger FET output (10Ω + 2200pF for ~40MHz filter, original design used 2Ω + 2200pF for 227MHz). 2) Add series resistance to high-side gate (R17, currently 0Ω). 3) Use 4-layer PCB with GND planes on layers 2 and 3. 4) Consider board-level EMI shield can over charging circuit. 5) Minimize high-current loop area. 6) Use ferrite beads on power input (parallel for lower impedance).",
    affectedComponents: ["BQ24610"],
    sourceProject: "Devon-REC Nidek Battery Pack",
    severity: "critical",
    status: "approved",
    addedDate: "2026-02-28",
  },
  {
    id: "ll-017",
    title: "BQ40Z50 all hardware revisions are same silicon — firmware only",
    category: "component-issue",
    description: "BQ40Z50, R1, R2, R3, and R4 are all the same IC die, differentiated only by firmware",
    whatHappened: "Team was sourcing only BQ40Z50-R2 parts, turning away -R1 and base BQ40Z50 parts from vendors. When attempting to rework boards, couldn't tell if parts had been swapped because IC markings looked identical.",
    rootCause: "TI documentation confirms all revisions share the same hardware. The R2 version shows as firmware identification in BQStudio, not a hardware marking. BQ40Z50 can be upgraded to R4 by simply flashing the v4.02 .SREC firmware file. The .BQZ config file must be placed in BQStudio's config folder for R4 to appear as an option.",
    fix: "Accept any BQ40Z50 revision (base, R1, R2, R3) and flash to R4 firmware. This vastly opens up the supply chain. Do verify new firmware features work on older silicon by testing a specific R4 feature after flashing. TI app note SLUAAE2 confirms hardware compatibility.",
    affectedComponents: ["BQ40Z50"],
    sourceProject: "Devon-REC Nidek/U1 Battery Pack",
    severity: "minor",
    status: "approved",
    addedDate: "2026-02-28",
  },
  {
    id: "ll-018",
    title: "Outer cells in series pack discharge faster than inner cells",
    category: "design-error",
    description: "Cell 1 and Cell 4 in a 4S LiFePO4 pack fall faster during discharge than cells 2 and 3",
    whatHappened: "During U1 battery discharge testing, the CUV (cell undervoltage) flag was set because cells 1 and 4 dropped below threshold while cells 2 and 3 still had capacity remaining.",
    rootCause: "Outer cells in a series stack have different thermal environments — they lose heat to the enclosure walls while inner cells benefit from mutual insulation. Temperature affects LiFePO4 discharge curves. Additionally, initial charge may not have reached full capacity plateau for the outer cells.",
    fix: "1) Charge packs long enough to get past the full capacity plateau on all cells. 2) Enable passive cell balancing in the BQ40Z50 firmware. 3) Set CUV thresholds with margin for cell imbalance. 4) Monitor individual cell voltages during qualification, not just pack voltage. 5) Consider thermal management or insulation design to equalize cell temperatures.",
    affectedComponents: ["BQ40Z50", "LiFePO4-32650"],
    sourceProject: "Devon-REC U1 Battery Pack",
    severity: "major",
    status: "approved",
    addedDate: "2026-02-28",
  },
  {
    id: "ll-019",
    title: "Golden file must not auto-enable FETs, fuse, or gauge",
    category: "manufacturing",
    description: "Production golden SREC file should not automatically initialize safety-critical systems",
    whatHappened: "Packs programmed with golden file had FETs enabled before being married to cells, causing issues during assembly. Some packs on the shelf at Nidek had problems waiting to be combined with NuvoNanos.",
    rootCause: "The golden file enabled FETs, fuse protection, black box recording, permanent failure detection, and gauge functions automatically on programming. These systems should only be activated after the pack is assembled with cells and validated.",
    fix: "Golden file should leave these systems disabled by default. Post-programming activation sequence: 1) Program golden SREC, 2) Assemble cells to board, 3) Validate cell connections and voltages, 4) Enable FETs (FET_EN), 5) Enable gauge (GAUGE_EN), 6) Enable remaining protections. This prevents issues with packs stored between programming and final assembly.",
    affectedComponents: ["BQ40Z60", "BQ40Z50"],
    sourceProject: "Devon-REC Nidek Battery Pack",
    severity: "major",
    status: "approved",
    addedDate: "2026-02-28",
  },
  {
    id: "ll-020",
    title: "Ethernet cable parasitic drain on BMS — 3.6mA vs 90.7μA",
    category: "field-failure",
    description: "Battery pack with connected ethernet cable draws 40x more current than disconnected",
    whatHappened: "U1 battery packs were draining faster than expected in storage and field use.",
    rootCause: "With ethernet cable connected, the BMS board draws 3.6mA continuously. Without cable, it drops to 90.7μA. The SMBus pull-ups and communication interface on the ethernet cable create a constant current path. Combined with sleep mode being disabled in the Kingon golden file.",
    fix: "1) Enable sleep mode in production golden file (Kingon had it disabled). 2) Account for cable parasitic drain in battery capacity reserve calculations — reserve more than 5.5Ah for storage. 3) Consider adding a physical disconnect or low-power sleep mode triggered by no host communication.",
    affectedComponents: ["BQ40Z50"],
    sourceProject: "Devon-REC U1 Battery Pack",
    severity: "major",
    status: "approved",
    addedDate: "2026-02-28",
  },
];
