import { LessonLearned } from "../types/index.js";

// ── Hard-won knowledge from real projects ──
// This is the most valuable file in the server.
// Every entry here prevents a future engineer from repeating a mistake.

export const lessonsLearned: LessonLearned[] = [
  {
    id: "ll-001",
    title: "ESP32 WiFi drops with distant decoupling",
    category: "design-error",
    description: "WiFi TX power drops and connection instability when bulk decoupling cap is too far from VDD pins",
    whatHappened: "Asset tracker rev A had intermittent WiFi disconnects under load. Signal strength measured 8dBm below expected.",
    rootCause: "10uF bulk capacitor was placed 25mm from ESP32 VDD3P3 pins due to layout constraints. High-frequency switching noise on the 3.3V rail during WiFi TX.",
    fix: "Moved 10uF bulk cap within 10mm of VDD pins. Added second 100nF directly at VDD3P3_RTC pin. Rev B fixed the issue completely.",
    affectedComponents: ["ESP32-S3-WROOM-1"],
    affectedCircuits: ["esp32-s3-base"],
    sourceProject: "PROJ-2024-017 Asset Tracker",
    severity: "major",
    status: "approved",
    addedDate: "2026-02-28",
  },

  // ── Carter-Hoffmann M-Series Lessons (from Slack archive 2020-2025) ──

  {
    id: "ll-002",
    title: "Telco cable quality causes intermittent display flicker",
    category: "manufacturing",
    description: "6-pin telco (RJ11) cable quality caused years of intermittent display flicker on M-Series holding cabinets",
    whatHappened: "Alphanumeric display boards flickered intermittently, especially in passthrough cabinets (M343) with master+slave configurations. Problem appeared random and was extremely difficult to reproduce consistently.",
    rootCause: "Cable manufacturing defects: outer insulation stripped too far back (~1/2\" instead of ~1/4\"), strain relief not engaged during crimping, connector alignment off causing deformed plastic in contact channels. Added capacitance from poor cables created crosstalk on shift register clock/data lines.",
    fix: "1) Specified Assmann WSW A-MO-6-6-F50 plugs with proper crimping procedure. 2) Wire spec: 26AWG with proper insulation thickness, strain relief MUST be engaged. 3) Changed HC08 AND gate ICs to faster HCS08 across all display boards (FGLF0598-03→05, FGLF0599-03→05, FGLF0626-00→01, FGLF0627-00→01). Tony tested 252 combinations (7 boards, 36 cables, 9 plug types) to prove root cause.",
    affectedComponents: ["HC08", "HCS08", "RJ11"],
    affectedCircuits: ["m-series-display"],
    sourceProject: "Carter-Hoffmann M-Series (rma_flicker)",
    severity: "critical",
    status: "approved",
    addedDate: "2026-02-28",
  },
  {
    id: "ll-003",
    title: "Faster logic IC fix introduced new button detection bug",
    category: "component-issue",
    description: "Swapping to faster AND gate ICs fixed display flicker but broke button responsiveness on downstream single-window displays",
    whatHappened: "After changing HC08 AND gates to faster HCS08 to fix flicker, timer buttons on single-window displays became unresponsive when daisy-chained downstream of dual-window master boards.",
    rootCause: "The faster HCS08 propagation delay changed the timing relationship between shift register clock and data lines. Single-window displays downstream of dual-window masters saw different timing margins than the original HC08 design was tuned for.",
    fix: "Required stocking two different driver IC variants — HCS08 for boards that don't chain to single-window displays, and HC08 + trace jumper for boards that do. Full regression testing across ALL board configurations is mandatory for any logic IC substitution.",
    affectedComponents: ["HC08", "HCS08"],
    affectedCircuits: ["m-series-display"],
    sourceProject: "Carter-Hoffmann M-Series (rma_flicker)",
    severity: "major",
    status: "approved",
    addedDate: "2026-02-28",
  },
  {
    id: "ll-004",
    title: "Power supply failures at full load in passthrough cabinets",
    category: "field-failure",
    description: "FGLF0604-01 power supply boards failing after 30-60 minutes under full load",
    whatHappened: "PSU boards in M343 passthrough cabinets (worst-case: 15 heaters, controls on both front and back) showed black marks near X3 and failed after 30 min to 1 hour. Failure rate escalated from 1-2 units to multiple per batch of 30.",
    rootCause: "Dual transformer power supply variant was being tested with single-transformer load levels. Actual load in M343 passthrough is nearly double what was tested.",
    fix: "Double test load for dual-transformer variant. Extended full-load test procedure: use test firmware to light every display segment, run maximum boards for 1+ hour. Measure DC current on red wire from PSU to breakout board.",
    affectedComponents: ["FGLF0604-01"],
    affectedCircuits: ["m-series-psu"],
    sourceProject: "Carter-Hoffmann M343",
    severity: "critical",
    status: "approved",
    addedDate: "2026-02-28",
  },
  {
    id: "ll-005",
    title: "EMI from AC fan motor caused overvoltage board damage",
    category: "field-failure",
    description: "Display boards at Popeyes location found charred with ICs violently decapped from overvoltage",
    whatHappened: "Multiple display boards destroyed — low-voltage ICs showed signs of catastrophic overvoltage. No visible damage to power supply or controller board.",
    rootCause: "AC muffin fan (208V) with motor start capacitor was mounted adjacent to power supply. Fan power cord was laying directly on the PSU wire harness. EMI from fan motor likely coupled into the DC supply, causing false switching and voltage spikes. Telco signal cables routed too close to AC power lines amplified the problem.",
    fix: "1) Route display/signal cables AWAY from AC voltage sources. 2) Use ferrite coils on signal wires near power entry. 3) Consider shielded cables for signal runs near AC. 4) Use nylon standoff nuts instead of metal keps nuts to reduce ground loop paths. 5) Add dielectric sleeving where signal and power wires must cross.",
    affectedComponents: ["FGLF0598", "FGLF0599"],
    sourceProject: "Carter-Hoffmann Popeyes Field Failure",
    severity: "critical",
    status: "approved",
    addedDate: "2026-02-28",
  },
  {
    id: "ll-006",
    title: "USB drive compatibility varies widely with embedded USB host",
    category: "component-issue",
    description: "Not all USB drives work with PIC-based embedded USB host controller",
    whatHappened: "Specific USB drives failed to be recognized by USBHost Mux board for firmware loading. Some drives worked for one engineer but not another.",
    rootCause: "Embedded USB host stack on PIC has limited device compatibility. No full OS to provide driver abstraction for different USB flash controller chipsets. Different USB drive manufacturers use different internal controllers.",
    fix: "Qualify specific USB drive models and stick with them. Document known-good drive models. Do not guarantee compatibility with arbitrary drives. To truly support all hardware would require an OS on the embedded system.",
    affectedComponents: ["PIC-USB-Host"],
    sourceProject: "Carter-Hoffmann WAWA (usb-host)",
    severity: "minor",
    status: "approved",
    addedDate: "2026-02-28",
  },
  {
    id: "ll-007",
    title: "Bootloader size change makes firmware images incompatible",
    category: "design-error",
    description: "Increasing bootloader from 19KB to 24KB for ConnectWare support created incompatible firmware images",
    whatHappened: "Adding PowerHouse Dynamics ConnectWare support required a larger bootloader (24KB vs original 19KB). Firmware built for one bootloader size would not work with the other.",
    rootCause: "The 5KB size difference shifts the application start address. Firmware images are not self-describing — they assume a fixed bootloader size. Old firmware flashed onto a board with the new bootloader writes to the wrong addresses.",
    fix: "Created two separate part numbers: FGLF0605-01 (standard, 19KB bootloader) and FGLF0605-02 (ConnectWare, 24KB bootloader). Firmware versions for new bootloader start at 4.xx to make version incompatibility obvious. Plan bootloader size for maximum expected future needs from the start.",
    affectedComponents: ["PIC-bootloader"],
    sourceProject: "Carter-Hoffmann ConnectWare Integration",
    severity: "major",
    status: "approved",
    addedDate: "2026-02-28",
  },
  {
    id: "ll-008",
    title: "Shift register comms over telco cables should use shielded twisted pair",
    category: "design-error",
    description: "6-pin telco cables are fundamentally unreliable for cascaded digital communication",
    whatHappened: "Years of intermittent failures, flicker, and signal integrity issues across the entire M-Series product line traced back to using unshielded flat telco cables for shift register clock/data signals.",
    rootCause: "RJ11 telco cables are designed for analog voice, not digital data. No shielding, no twisted pairs, inconsistent manufacturing quality, poor retention force. Cable capacitance varies wildly between manufacturers and even between batches.",
    fix: "For any new design with cascaded digital communication: use 8-pin CAT-5e/Ethernet connectors with shielded twisted pairs. Standard ethernet cables are manufactured in volume on precise equipment that eliminates crimping variation. RJ45 jacks have better retention than RJ11. Budget the extra connector cost — it's far cheaper than years of field failures.",
    affectedCircuits: ["m-series-display", "m-series-comms"],
    sourceProject: "Carter-Hoffmann M-Series (all channels)",
    severity: "critical",
    status: "approved",
    addedDate: "2026-02-28",
  },
  {
    id: "ll-009",
    title: "NTC sensor short detection threshold too aggressive for cold environments",
    category: "design-error",
    description: "Temperature sensor short detection flagging false errors in cold startup conditions",
    whatHappened: "NTX Cook-and-Hold software v2 flagged anything under 1000 ohm as a shorted temperature sensor, which corresponds to about 32°F. Units in cold environments (loading docks, unheated kitchens) threw false short errors on startup.",
    rootCause: "Short detection threshold was set too close to the low end of normal operating range. 1000 ohm on an NTC thermistor corresponds to approximately 32°F — a temperature that equipment could realistically encounter.",
    fix: "Changed short detection threshold from 1000 ohm to 500 ohm in firmware v3. This allows minimum temperature reading down to -125°C before reporting a short. Lowest displayed temperature is 1°F. Trade-off: less accurate detection of actual shorts below freezing, but prevents false errors in realistic cold environments.",
    affectedComponents: ["NTC-thermistor"],
    sourceProject: "Carter-Hoffmann NTX Cook-and-Hold",
    severity: "major",
    status: "approved",
    addedDate: "2026-02-28",
  },
  {
    id: "ll-010",
    title: "Removing firmware state without full cleanup causes undefined behavior",
    category: "design-error",
    description: "Removing PROGRAM_ADJUST mode from firmware without cleaning all references caused display freeze",
    whatHappened: "After removing PROGRAM_ADJUST mode to fix timer button delay, pressing up/down arrows during NOT_AT_SETPOINT (warmup) state caused the drawer display to enter an undefined state with no exit — complete display freeze.",
    rootCause: "References to the removed PROGRAM_ADJUST mode were not completely cleaned up from the NOT_AT_SETPOINT state handler. The state machine transitioned to a state that no longer existed.",
    fix: "Eliminated ALL remaining PROGRAM_ADJUST mode references across every state in the firmware (v3.03). When removing a state from a state machine, grep the entire codebase for every reference — transitions into, out of, and guards checking for that state.",
    sourceProject: "Carter-Hoffmann WAWA v3.03",
    severity: "major",
    status: "approved",
    addedDate: "2026-02-28",
  },
];
