import { ProgrammingInterface } from "../types/index.js";

// Hand-crafted from field-updater project data — REC programming interfaces

export const programmingInterfaces: ProgrammingInterface[] = [
  {
    id: "prog-pogo-array",
    name: "REC POGO Array (4x4)",
    type: "pogo",
    mcuFamilies: ["ESP32", "RP2040", "PIC18"],
    pinCount: 16,
    pitch: 1.27,
    pins: [
      { pin: 1, function: "VCC (3.3V)", mcuPin: "VDD/3V3", notes: "Shared with TC pin 6" },
      { pin: 2, function: "GND", mcuPin: "VSS/GND" },
      { pin: 3, function: "DATA_A (TX)", mcuPin: "RX (ESP32: GPIO3, PIC18: varies)", notes: "Shared with TC pin 2" },
      { pin: 4, function: "DATA_B (RX)", mcuPin: "TX (ESP32: GPIO1, PIC18: varies)", notes: "Shared with TC pin 3" },
      { pin: 5, function: "BOOT/EN", mcuPin: "ESP32: GPIO0, RP2040: BOOTSEL", notes: "Shared with TC pin 5. LOW = download mode for ESP32" },
      { pin: 6, function: "RST/MCLR", mcuPin: "ESP32: EN, PIC18: MCLR, RP2040: RUN", notes: "Shared with TC pin 1" },
      { pin: 7, function: "ADDR0", mcuPin: "N/A", notes: "Future multi-board fixture addressing" },
      { pin: 8, function: "ADDR1", mcuPin: "N/A", notes: "Future multi-board fixture addressing" },
      { pin: 9, function: "ADDR2", mcuPin: "N/A", notes: "Future multi-board fixture addressing" },
      { pin: 10, function: "ID0", mcuPin: "N/A", notes: "Board ID solder jumper. Bridge to GND = 0, open = 1" },
      { pin: 11, function: "ID1", mcuPin: "N/A", notes: "Board ID solder jumper" },
      { pin: 12, function: "ID2", mcuPin: "N/A", notes: "Board ID solder jumper" },
      { pin: 13, function: "ID3", mcuPin: "N/A", notes: "Board ID solder jumper. ID 0-14 valid, 15 = no board" },
      { pin: 14, function: "RSV1 (SWCLK/PGD)", mcuPin: "PIC18: PGD, RP2040: SWCLK", notes: "Shared with TC pin 4" },
      { pin: 15, function: "RSV2", mcuPin: "N/A", notes: "Reserved for future use" },
      { pin: 16, function: "RSV3", mcuPin: "N/A", notes: "Reserved for future use" },
    ],
    footprint: "POGO_ARRAY_4X4",
    libraryFile: "REC_Pogo_Array.lbr",
    description: "16-pin (4x4 grid) board-mounted programming interface with magnetic fixture. Replaces Tag-Connect TC2030. Supports ESP32 (UART boot), RP2040 (SWD), PIC18 (ICSP LVP). Includes 4-bit board ID via solder jumpers (0-14, 15=reserved).",
    protocol: "Auto-detect: reads board ID pins → detects MCU type → selects UART/SWD/ICSP protocol",
    notes: "Pad diameter: 1.0mm SMD circular. Alignment holes: 1.5mm NPTH. Steel pads: 6mm for N52 magnets. Add BOARD_ID_CONFIG_4BIT solder jumper block alongside.",
  },
  {
    id: "prog-tag-connect-tc2030",
    name: "Tag-Connect TC2030 (6-pin)",
    type: "tag-connect",
    mcuFamilies: ["ESP32", "RP2040", "PIC18"],
    pinCount: 6,
    pitch: 1.27,
    pins: [
      { pin: 1, function: "MCLR/GND", mcuPin: "PIC18: MCLR, ESP32: GND", notes: "Function depends on MCU type" },
      { pin: 2, function: "VDD/TX", mcuPin: "PIC18: VDD, ESP32: TX", notes: "Function depends on MCU type" },
      { pin: 3, function: "GND/RX", mcuPin: "PIC18: GND, ESP32: RX", notes: "Function depends on MCU type" },
      { pin: 4, function: "PGD/SWCLK", mcuPin: "PIC18: PGD, RP2040: SWCLK" },
      { pin: 5, function: "PGC/SWDIO", mcuPin: "PIC18: PGC, RP2040: SWDIO" },
      { pin: 6, function: "3.3V", mcuPin: "VDD/3V3", notes: "Power output from programmer" },
    ],
    footprint: "TC2030-IDC",
    description: "Legacy 6-pin no-legs cable connector for firmware programming. Being replaced by POGO array on future designs. Still supported by field updater auto-detection.",
    protocol: "Auto-detect via ground pin probing: Pin 1 GND = ESP32/RP2040, Pin 3 GND = PIC18",
    notes: "Requires manual cable connection. Pogo pins 1-6 mirror TC pins for backward compatibility.",
  },
  {
    id: "prog-icsp-pic18",
    name: "PIC18 ICSP (LVP)",
    type: "icsp",
    mcuFamilies: ["PIC18", "PIC16", "PIC12"],
    pinCount: 5,
    pins: [
      { pin: 1, function: "MCLR", mcuPin: "MCLR/VPP", notes: "Master clear / programming enable. Hold LOW to enter prog mode." },
      { pin: 2, function: "VDD", mcuPin: "VDD", notes: "3.3V or 5V depending on PIC variant" },
      { pin: 3, function: "GND", mcuPin: "VSS" },
      { pin: 4, function: "PGD", mcuPin: "PGD (RB7 typically)", notes: "Bidirectional program data" },
      { pin: 5, function: "PGC", mcuPin: "PGC (RB6 typically)", notes: "Program clock, driven by programmer" },
    ],
    description: "PIC18 In-Circuit Serial Programming using Low Voltage Programming mode. 33-bit MCHP key sequence (0x4D434850) to enter programming mode.",
    protocol: "ICSP LVP: MCLR LOW → 33-bit key → MCLR HIGH → 4-bit opcodes + 24-bit data. Read device ID at 0x3FFFFE.",
    notes: "100ns setup/hold times, 1us delays. PIC18F26K22 is most common REC PIC (31 instances).",
  },
  {
    id: "prog-swd-rp2040",
    name: "RP2040 SWD",
    type: "swd",
    mcuFamilies: ["RP2040", "STM32"],
    pinCount: 3,
    pins: [
      { pin: 1, function: "SWCLK", mcuPin: "SWCLK", notes: "Serial Wire Clock" },
      { pin: 2, function: "SWDIO", mcuPin: "SWDIO", notes: "Serial Wire Data I/O (bidirectional)" },
      { pin: 3, function: "RST", mcuPin: "RUN (RP2040) / NRST (STM32)", notes: "Optional reset" },
    ],
    description: "ARM Serial Wire Debug for RP2040 and STM32. JTAG-to-SWD switch sequence, then register-level debug port access.",
    protocol: "SWD: 56 clocks HIGH → 0x79E7 sequence → 56 clocks → idle. Read IDCODE (RP2040: 0x0BC12477). OpenOCD for flash programming.",
    notes: "RP2040 also supports UF2 drag-and-drop via USB mass storage mode (BOOTSEL button).",
  },
  {
    id: "prog-uart-esp32",
    name: "ESP32 UART Bootloader",
    type: "uart-boot",
    mcuFamilies: ["ESP32"],
    pinCount: 4,
    pins: [
      { pin: 1, function: "TX", mcuPin: "GPIO1 (U0TXD)", notes: "ESP32 transmit → programmer receive" },
      { pin: 2, function: "RX", mcuPin: "GPIO3 (U0RXD)", notes: "Programmer transmit → ESP32 receive" },
      { pin: 3, function: "GPIO0/BOOT", mcuPin: "GPIO0", notes: "Hold LOW during reset to enter download mode" },
      { pin: 4, function: "EN/RST", mcuPin: "EN", notes: "Chip enable / reset. Pulse LOW to reset." },
    ],
    description: "ESP32 UART bootloader programming. GPIO0 LOW during reset enters download mode. SLIP-encoded commands for flash operations.",
    protocol: "SLIP framing: sync (0x07 0x07 0x12 0x20 + 32x 0x55), then flash_begin/flash_data/flash_end commands. MD5 verification.",
    notes: "Default baud 115200, can change to 921600 after sync. ESP32-S3/C3/C6 use similar but with USB-CDC option.",
  },
  {
    id: "prog-pogo-board-id",
    name: "POGO Board ID (4-bit Solder Jumpers)",
    type: "pogo",
    mcuFamilies: ["ESP32", "RP2040", "PIC18"],
    pinCount: 4,
    pins: [
      { pin: 1, function: "ID0 (LSB)", mcuPin: "N/A", notes: "Solder bridge to GND = 0, leave open = 1 (pull-up)" },
      { pin: 2, function: "ID1", mcuPin: "N/A", notes: "Solder bridge to GND = 0, leave open = 1" },
      { pin: 3, function: "ID2", mcuPin: "N/A", notes: "Solder bridge to GND = 0, leave open = 1" },
      { pin: 4, function: "ID3 (MSB)", mcuPin: "N/A", notes: "Solder bridge to GND = 0, leave open = 1" },
    ],
    footprint: "BOARD_ID_CONFIG_4BIT",
    libraryFile: "REC_Pogo_Array.lbr",
    description: "4-bit solder jumper block for board identification. Valid IDs: 0-14. ID 15 (all open) = 'no board connected' (reserved). Place alongside POGO_ARRAY_4X4 footprint.",
    protocol: "Programmer reads ID pins with internal pull-ups. All HIGH (15) = no board. Any LOW bit = board detected with that ID.",
    notes: "Horizontal (BOARD_ID_CONFIG_4BIT) or vertical (BOARD_ID_CONFIG_4BIT_VERT) layout options available.",
  },
];
