import { SubstitutionRule } from "../types/index.js";

// ── Verified component substitutions ──
// When a part is out of stock, these tell the system what's safe to swap in.

export const substitutionRules: SubstitutionRule[] = [
  {
    id: "sub-001",
    originalPart: "RC0402FR-0710KL",
    substitutePart: "CRCW040210K0FKED",
    conditions: "Direct drop-in. Same value, tolerance, package. Vishay instead of Yageo.",
    verified: true,
    verifiedOn: "PROJ-2025-003",
    status: "approved",
    addedDate: "2026-02-28",
  },
  {
    id: "sub-002",
    originalPart: "AMS1117-3.3",
    substitutePart: "AP2112K-3.3TRG1",
    conditions: "Pin-compatible 3.3V LDO. Lower current (600mA vs 1A) but lower quiescent current. OK for designs under 500mA.",
    verified: true,
    verifiedOn: "PROJ-2025-008",
    limitations: "Max output 600mA vs 1A. Check load requirements.",
    status: "approved",
    addedDate: "2026-02-28",
  },

  // ── Carter-Hoffmann TRIAC Substitutions (from Slack archive) ──

  {
    id: "sub-003",
    originalPart: "BTA12-600BWRG",
    substitutePart: "BTA12-700BWRG",
    conditions: "Same package and pinout. Higher voltage rating (700V vs 600V). Verified drop-in replacement for M-Series triac boards.",
    verified: true,
    verifiedOn: "Carter-Hoffmann M-Series",
    limitations: "Requires UL file update when substituting. Derate to 5A max in production.",
    status: "approved",
    addedDate: "2026-02-28",
  },
  {
    id: "sub-004",
    originalPart: "BTA12-600BWRG",
    substitutePart: "BTA12-800BWRG",
    conditions: "Same package and pinout. Higher voltage rating (800V vs 600V). Verified drop-in replacement for M-Series triac boards.",
    verified: true,
    verifiedOn: "Carter-Hoffmann M-Series",
    limitations: "Requires UL file update when substituting. Derate to 5A max in production.",
    status: "approved",
    addedDate: "2026-02-28",
  },
  {
    id: "sub-005",
    originalPart: "CH340G",
    substitutePart: "CH340C",
    conditions: "Crystal-less variant — eliminates external 12MHz crystal. Same USB-serial functionality, easier layout for small boards.",
    verified: true,
    verifiedOn: "REC internal",
    limitations: "Internal oscillator slightly less accurate than crystal — acceptable for UART communication, not for precision timing.",
    status: "approved",
    addedDate: "2026-02-28",
  },

  // ── FullVision / Trackmaster Medical Treadmill Substitutions (from Slack archive 2019-2025) ──

  {
    id: "sub-006",
    originalPart: "IRLML6402",
    substitutePart: "BSS84P",
    conditions: "NOT a bidirectional substitution. BSS84P is the CORRECT part for the magnetic pull tether Q1 position. IRLML6402 causes safety-critical latch-up. Both are SOT-23 P-channel MOSFETs but Vgs(th) differs. BSS84P marked 'SP.'/'YBs', IRLML6402 marked 'EABN9'.",
    verified: true,
    verifiedOn: "FullVision Trackmaster Treadmill",
    limitations: "THIS IS A SAFETY-CRITICAL CORRECTION, not a substitution. IRLML6402 must ALWAYS be replaced with BSS84P in the tether circuit. 320 boards were affected. FDA-reportable.",
    status: "approved",
    addedDate: "2026-02-28",
  },
  {
    id: "sub-007",
    originalPart: "RL0015",
    substitutePart: "HATF901ASDC12-1",
    conditions: "Hasco relay, same coil voltage (12VDC) and footprint. Drop-in replacement for elevation relay during RL0015 shortage.",
    verified: true,
    verifiedOn: "FullVision Trackmaster Treadmill",
    limitations: "Verify contact isolation voltage meets application requirements. RL0015 and substitute both have limited isolation — insufficient for 4.3kV hipot without external contactor.",
    status: "approved",
    addedDate: "2026-02-28",
  },
  {
    id: "sub-008",
    originalPart: "FTDI-USB-TTL",
    substitutePart: "Cypress-USB-TTL",
    conditions: "Cypress USB-to-serial IC as substitute for FTDI during FTDI shortage. Same USB-serial functionality for treadmill RS-232 communication interface.",
    verified: true,
    verifiedOn: "FullVision Trackmaster Treadmill",
    limitations: "Requires different device driver on host side. Verify driver compatibility with GE CASE system before deployment. Windows driver installation may differ.",
    status: "approved",
    addedDate: "2026-02-28",
  },

  // ── FullVision Quantum Drive Substitutions (from Slack archive quantum-guest-channel 2023) ──

  {
    id: "sub-009",
    originalPart: "MKV31F512",
    substitutePart: "MKV31F256",
    conditions: "ONLY on Rev C (R0C) drive boards which have rerouted traces for the missing timer peripheral. R0C boards support EITHER processor with the same firmware binary. Rev A/B (R0B) boards are 512KB ONLY.",
    verified: true,
    verifiedOn: "FullVision Quantum Treadmill (quantum-guest-channel)",
    limitations: "256KB variant missing one timer used for input capture — requires PCB trace change (R0C revision). Firmware version reporting differs: v4.x = 512KB, v5.x = 256KB. Calibration software reports 1026 for v4.2 (512KB) and 1280 for v5.0 (256KB). Must select correct target device (MKV31F256 vs MKV31F512) in J-Flash Lite when programming.",
    status: "approved",
    addedDate: "2026-02-28",
  },

  // ── SBI (Stove Builder International) Substitutions (from Slack archive 2015-2024) ──

  {
    id: "sub-010",
    originalPart: "BTA12-600BWRG",
    substitutePart: "T1620T",
    conditions: "Direct drop-in replacement on existing triac boards. Same package (TO-220). Higher rating: 16A/800V vs 12A/600V. Temperature improved from 293°F to 237°F on setting 5 (no airflow) and 248°F to 184°F on setting 3.",
    verified: true,
    verifiedOn: "SBI Alterna-II / Wood Furnace Triac Boards",
    limitations: "Does not eliminate root cause of multi-tap motor transformer backfeed. Provides thermal margin improvement only. Custom heatsink (186°F) was more cost-effective. Relay hybrid board is the permanent fix.",
    status: "approved",
    addedDate: "2026-03-02",
  },
  {
    id: "sub-011",
    originalPart: "BTA12-600BWRG",
    substitutePart: "T3035H-6I",
    conditions: "Used on relay hybrid board (PCBLF0467). 30A/800V rating, Tj max 150°C, Rth(j-c) 1.9°C/W. Preferred for availability and cost over Q6035RH5 (35A Littelfuse). NOT a drop-in for existing triac boards — requires relay hybrid board design.",
    verified: true,
    verifiedOn: "SBI Relay Hybrid Board (PCBLF0467-7)",
    limitations: "Only on relay hybrid board design where relays isolate unused motor taps. Tested at 80°C (speed 1, ~5A, Alterna-II) and 90°C (~8A, Max Caddy). Approved for production.",
    status: "approved",
    addedDate: "2026-03-02",
  },
  {
    id: "sub-012",
    originalPart: "F1-400mA-PTC",
    substitutePart: "F1-1.6A-PTC",
    conditions: "Link board polyswitch F1 upgrade for Serial Add-On configuration where total load exceeds 400mA (damper 333mA + relays 250mA + LCD 150mA + processor 50mA = ~783mA). New part number FGLF0622-02. Same footprint.",
    verified: true,
    verifiedOn: "SBI Wood Furnace Controllers (Serial Add-On mode)",
    limitations: "Only needed in Serial Add-On configuration. Standard configuration with power from Triac board uses F3 (1.6A) path. Field workaround: short F1 and add inline external fuse.",
    status: "approved",
    addedDate: "2026-03-02",
  },
  {
    id: "sub-013",
    originalPart: "PIC18F26K22",
    substitutePart: "PIC18F24K22",
    conditions: "Pin-compatible processor substitution during chip shortage. REQUIRES separate firmware compilation — POWER116.ROM for 26K22 will brick the 24K22 (continuous reboot, unrecoverable via bootloader). Must program with compatible firmware that reports v1.16, use LOAD bootloader command instead of BOOT, and add version subcode (1.16A) to distinguish.",
    verified: true,
    verifiedOn: "SBI Pellet Stove Triac/Power Boards (picolcd)",
    limitations: "THIS IS NOT A DROP-IN SUBSTITUTION for firmware. Hardware is pin-compatible but firmware must be recompiled. Must visually distinguish boards (different sticker/PCB color). LCD auto-update systems will brick the 24K22 if not protected.",
    status: "approved",
    addedDate: "2026-03-02",
  },
  {
    id: "sub-014",
    originalPart: "T9AS1D12-12",
    substitutePart: "AZ21501-1A-12DE",
    conditions: "American Zettler relay as substitute for TE Connectivity Potter & Brumfield T9AS1D12-12. Same coil voltage (12VDC) and contact rating. UL-listed substitution.",
    verified: true,
    verifiedOn: "SBI Wood Furnace / Low-Cost Fan Limit Board",
    limitations: "Zettler relay may have different back-EMF characteristics during de-energization. Some evidence of increased VR1 switching regulator sensitivity with Zettler relays (higher failure rate correlation, not conclusively proven). Test switching transient interaction with power supply before production commitment.",
    status: "approved",
    addedDate: "2026-03-02",
  },

  // ── Roanoke Controls Internal Substitutions (from roanokecontrols Slack archive 2015-2025) ──

  {
    id: "sub-015",
    originalPart: "Mean-Well-IRM-03-SMT",
    substitutePart: "Mean-Well-IRM-03-THT",
    conditions: "Through-hole version of Mean Well IRM-03 power supply brick to replace SMT version. Same electrical specifications. Through-hole provides superior mechanical attachment and more reliable solder joints.",
    verified: true,
    verifiedOn: "REC Pitts & Spitts Grill Controllers",
    limitations: "Through-hole version requires hand soldering or wave solder — cannot be placed by pick-and-place. Board layout must accommodate through-hole pad pattern. Slightly taller profile than SMT version.",
    status: "approved",
    addedDate: "2026-03-02",
  },
  {
    id: "sub-016",
    originalPart: "BQ40Z60",
    substitutePart: "BQ40Z50",
    conditions: "TI BMS IC replacement. BQ40Z60 is NRND (Not Recommended for New Designs). BQ40Z50 is the recommended replacement. Same battery management functionality with updated feature set.",
    verified: true,
    verifiedOn: "REC Nidek Medical BMS",
    limitations: "Register map and configuration differences — firmware must be updated. Verify gas gauge algorithm compatibility with battery chemistry. Pin-compatible but verify PCB footprint matches.",
    status: "approved",
    addedDate: "2026-03-02",
  },
  {
    id: "sub-017",
    originalPart: "IRL530",
    substitutePart: "IRL540",
    conditions: "WARNING: This is a CONDITIONAL substitution that FAILED in timing-sensitive circuits. Both are logic-level N-channel MOSFETs in TO-220 with similar voltage/current ratings. However, Vgs(th) differs significantly: IRL530 ~1.0V, IRL540 ~2.0V.",
    verified: true,
    verifiedOn: "REC Rottendog Pinball (FAILED)",
    limitations: "NOT SAFE for circuits with slow gate drive or limited overdrive voltage. Higher Vgs(th) of IRL540 causes later turn-on. Caused intermittent solenoid misfiring in pinball machines. Only acceptable in circuits with fast, high-voltage gate drivers where 1V Vgs(th) difference is irrelevant.",
    status: "approved",
    addedDate: "2026-03-02",
  },
  {
    id: "sub-018",
    originalPart: "RP-SMA-External-Antenna",
    substitutePart: "PCB-Trace-Antenna",
    conditions: "PCB trace antenna replaces external RP-SMA antenna for WiFi/BLE applications housed in plastic enclosures. Eliminates connector, cable, and external antenna hardware. Saves $0.75+ per unit.",
    verified: true,
    verifiedOn: "REC WiFi Grill Controllers (evaluation)",
    limitations: "Only suitable when PCB is inside a plastic enclosure extending beyond any metal housing. Metal enclosure completely blocks PCB antenna radiation. Must validate antenna gain and pattern for specific enclosure geometry. Range may be slightly reduced compared to high-gain external antenna.",
    status: "approved",
    addedDate: "2026-03-02",
  },
  {
    id: "sub-019",
    originalPart: "Phihong-PSAA05A-050QL6-R",
    substitutePart: "USB-5V-Power-Supply",
    conditions: "5V USB power supply (DigiKey 6560437) as alternative power input for grill controllers. Combined with USB extension cable for clean installation. Fastened to board with standoff for strain relief.",
    verified: true,
    verifiedOn: "REC Pitts & Spitts Grill Controllers",
    limitations: "USB cable routing must include strain relief (wrap around standoff). Verify USB supply can provide peak current for ESP32 WiFi TX bursts (500mA+). Cable length limited to 10ft for reliable 5V delivery under load.",
    status: "approved",
    addedDate: "2026-03-02",
  },
];
