import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { z } from "zod";
import { referenceCircuits, powerSupplies, protectionCircuits } from "../knowledge/index.js";
import { ScrBuilder } from "../generators/scr-builder.js";

export function registerGenerateSchematicScript(server: McpServer) {
  server.tool(
    "generate-schematic-script",
    "Generate a Fusion 360 Eagle SCR script file from reference circuit blocks. Uses REC_Standard_Library v365.lbr deviceset names for valid ADD commands. Save the output as a .scr file and run it in Fusion 360 Electronics via Automate > Script. For command reference, use the autodesk-coder MCP: get_ecad('Schematic Editor Commands').",
    {
      circuitId: z.string().optional().describe("Reference circuit ID to use as base (e.g. 'esp32-wrover-base')"),
      powerSupplyId: z.string().optional().describe("Power supply ID to include (e.g. 'usb-5v-to-3v3-ldo-ncp1117')"),
      protectionIds: z.array(z.string()).optional().describe("Protection circuit IDs to include"),
      sheetSize: z.enum(["A4", "A3", "A2", "letter", "tabloid"]).optional().default("A4"),
      blockSpacing: z.number().optional().default(300).describe("Spacing between blocks in mils"),
    },
    async ({ circuitId, powerSupplyId, protectionIds, sheetSize, blockSpacing }) => {
      const builder = new ScrBuilder();
      builder.addComment("Generated by rec-circuit-design MCP");
      builder.addComment(`Date: ${new Date().toISOString().split("T")[0]}`);
      builder.addComment("Parts from REC_Standard_Library v365.lbr");
      builder.addComment("");
      builder.useLibrary();
      builder.setGrid(100, "mil");
      builder.setSheet(1);

      let currentY = 2000; // Start placement from top

      // Place reference circuit blocks
      if (circuitId) {
        const circuit = referenceCircuits.find((rc) => rc.id === circuitId);
        if (circuit) {
          builder.addComment(`Reference Circuit: ${circuit.name}`);
          circuit.blocks.forEach((block, i) => {
            const originY = currentY - i * blockSpacing;
            builder.placeBlock(block, 500, originY);
          });
          currentY -= circuit.blocks.length * blockSpacing;
        } else {
          builder.addComment(`WARNING: Circuit ID "${circuitId}" not found`);
        }
      }

      // Place power supply
      if (powerSupplyId) {
        const power = powerSupplies.find((ps) => ps.id === powerSupplyId);
        if (power) {
          builder.addComment(`Power Supply: ${power.name}`);
          const powerBlock = {
            id: power.id,
            name: power.name,
            type: "power-regulation" as const,
            components: power.components,
            nets: power.nets,
          };
          builder.placeBlock(powerBlock, 500, currentY);
          currentY -= blockSpacing;
        }
      }

      // Place protection circuits
      if (protectionIds) {
        protectionIds.forEach((protId) => {
          const prot = protectionCircuits.find((pc) => pc.id === protId);
          if (prot) {
            builder.addComment(`Protection: ${prot.name}`);
            const protBlock = {
              id: prot.id,
              name: prot.name,
              type: "esd-protection" as const,
              components: prot.components,
              nets: prot.nets,
            };
            builder.placeBlock(protBlock, 500, currentY);
            currentY -= blockSpacing;
          }
        });
      }

      const script = builder.build();

      return {
        content: [
          {
            type: "text" as const,
            text: `Save the following as a .scr file and run in Fusion 360 Electronics via Automate > Script:\n\n\`\`\`\n${script}\n\`\`\``,
          },
        ],
      };
    }
  );
}
