import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { z } from "zod";
import { referenceCircuits, powerSupplies, protectionCircuits } from "../knowledge/index.js";
import { ScrBuilder } from "../generators/scr-builder.js";
import { getDesignBom, findDesign } from "../utils/design-loader.js";
import { DesignPart } from "../types/index.js";

// ── Component grouping helpers ──

const PREFIX_GROUPS: [string, string[]][] = [
  ["ICs & Modules", ["U", "A", "IC", "CR"]],
  ["Transistors & MOSFETs", ["Q", "T"]],
  ["Diodes", ["D", "LED"]],
  ["Resistors", ["R"]],
  ["Capacitors", ["C"]],
  ["Inductors & Transformers", ["L", "FL"]],
  ["Connectors", ["J", "X", "P", "CON"]],
  ["Relays & Switches", ["K", "RL", "S", "SW"]],
  ["Fuses & Protection", ["F"]],
  ["Crystals & Oscillators", ["Y", "OSC"]],
  ["Miscellaneous", []],
];

function groupParts(parts: DesignPart[]): { groupName: string; parts: DesignPart[] }[] {
  const assigned = new Set<number>();
  const groups: { groupName: string; parts: DesignPart[] }[] = [];

  for (const [groupName, prefixes] of PREFIX_GROUPS) {
    if (prefixes.length === 0) continue; // Miscellaneous handled last
    const matched: DesignPart[] = [];
    parts.forEach((part, idx) => {
      if (assigned.has(idx)) return;
      const refPrefix = part.ref.replace(/[0-9]+$/, "");
      if (prefixes.some((p) => refPrefix.toUpperCase() === p)) {
        matched.push(part);
        assigned.add(idx);
      }
    });
    if (matched.length > 0) {
      groups.push({ groupName, parts: matched });
    }
  }

  // Miscellaneous — anything unmatched
  const misc: DesignPart[] = [];
  parts.forEach((part, idx) => {
    if (!assigned.has(idx)) misc.push(part);
  });
  if (misc.length > 0) {
    groups.push({ groupName: "Miscellaneous", parts: misc });
  }

  return groups;
}

function collectLibraries(parts: DesignPart[]): string[] {
  const libs = new Set<string>();
  for (const p of parts) {
    if (p.library) libs.add(p.library);
  }
  return Array.from(libs).sort();
}

export function registerGenerateSchematicScript(server: McpServer) {
  server.tool(
    "generate-schematic-script",
    "Generate a Fusion 360 Eagle SCR script file from reference circuit blocks or from an existing REC design BOM. Uses REC_Standard_Library deviceset names for valid ADD commands. Save the output as a .scr file and run it in Fusion 360 Electronics via Automate > Script. For command reference, use the autodesk-coder MCP: get_ecad('Schematic Editor Commands').",
    {
      designName: z.string().optional().describe("Design name from REC library (e.g. 'TouchMZ_In_Out_Board'). Generates ADD commands for all components from that design."),
      circuitId: z.string().optional().describe("Reference circuit ID to use as base (e.g. 'esp32-wrover-base')"),
      powerSupplyId: z.string().optional().describe("Power supply ID to include (e.g. 'usb-5v-to-3v3-ldo-ncp1117')"),
      protectionIds: z.array(z.string()).optional().describe("Protection circuit IDs to include"),
      sheetSize: z.enum(["A4", "A3", "A2", "letter", "tabloid"]).optional().default("A4"),
      blockSpacing: z.number().optional().default(300).describe("Spacing between blocks in mils"),
    },
    async ({ designName, circuitId, powerSupplyId, protectionIds, sheetSize, blockSpacing }) => {
      const builder = new ScrBuilder();
      builder.addComment("Generated by rec-circuit-design MCP");
      builder.addComment(`Date: ${new Date().toISOString().split("T")[0]}`);

      // ── Design-name path ──
      // When designName is provided AND no block IDs are given, generate from design BOM.
      // If block IDs are also provided, they take precedence and designName components
      // are appended after the block placements.

      const hasBlockIds = !!(circuitId || powerSupplyId || protectionIds?.length);

      // Track where we are on the sheet
      let currentY = 2000;
      const COLS = 4;
      const COL_SPACING = 250;
      const ROW_SPACING = 200;

      if (hasBlockIds) {
        // ── Block-ID flow (existing behavior) ──
        builder.addComment("Parts from REC_Standard_Library");
        builder.addComment("");
        builder.useLibrary();
        builder.setGrid(100, "mil");
        builder.setSheet(1);

        if (circuitId) {
          const circuit = referenceCircuits.find((rc) => rc.id === circuitId);
          if (circuit) {
            builder.addComment(`Reference Circuit: ${circuit.name}`);
            circuit.blocks.forEach((block, i) => {
              const originY = currentY - i * blockSpacing;
              builder.placeBlock(block, 500, originY);
            });
            currentY -= circuit.blocks.length * blockSpacing;
          } else {
            builder.addComment(`WARNING: Circuit ID "${circuitId}" not found`);
          }
        }

        if (powerSupplyId) {
          const power = powerSupplies.find((ps) => ps.id === powerSupplyId);
          if (power) {
            builder.addComment(`Power Supply: ${power.name}`);
            const powerBlock = {
              id: power.id,
              name: power.name,
              type: "power-regulation" as const,
              components: power.components,
              nets: power.nets,
            };
            builder.placeBlock(powerBlock, 500, currentY);
            currentY -= blockSpacing;
          }
        }

        if (protectionIds) {
          protectionIds.forEach((protId) => {
            const prot = protectionCircuits.find((pc) => pc.id === protId);
            if (prot) {
              builder.addComment(`Protection: ${prot.name}`);
              const protBlock = {
                id: prot.id,
                name: prot.name,
                type: "esd-protection" as const,
                components: prot.components,
                nets: prot.nets,
              };
              builder.placeBlock(protBlock, 500, currentY);
              currentY -= blockSpacing;
            }
          });
        }

        // If designName is ALSO provided, merge its parts below the blocks
        if (designName) {
          const bom = await getDesignBom(designName);
          if (bom && bom.length > 0) {
            currentY -= 100; // Extra gap before design parts
            builder.addComment("");
            builder.addComment(`── Additional parts from design: ${designName} ──`);
            currentY = placeDesignParts(builder, bom, 500, currentY, COLS, COL_SPACING, ROW_SPACING);
          }
        }
      } else if (designName) {
        // ── Design-name-only path ──
        const bom = await getDesignBom(designName);

        if (!bom) {
          // Design not found — suggest alternatives
          const suggestions = await findDesign(designName);
          const suggestionText = suggestions.length > 0
            ? `Did you mean one of these?\n${suggestions.map((s) => `  - ${s.name} (score: ${s.score.toFixed(2)})`).join("\n")}`
            : "No similar design names found.";

          return {
            content: [
              {
                type: "text" as const,
                text: `Design "${designName}" not found in master.json.\n\n${suggestionText}`,
              },
            ],
          };
        }

        if (bom.length === 0) {
          return {
            content: [
              {
                type: "text" as const,
                text: `Design "${designName}" has no placeable components (only supply/frame symbols).`,
              },
            ],
          };
        }

        builder.addComment(`Design: ${designName}`);
        builder.addComment(`Components: ${bom.length}`);
        builder.addComment("");

        // USE all required libraries
        const libs = collectLibraries(bom);
        builder.setGrid(100, "mil");
        builder.setSheet(1);
        for (const lib of libs) {
          builder.useLibrary(lib);
        }
        builder.addComment("");

        placeDesignParts(builder, bom, 500, currentY, COLS, COL_SPACING, ROW_SPACING);
      } else {
        // Nothing provided
        return {
          content: [
            {
              type: "text" as const,
              text: "No designName, circuitId, powerSupplyId, or protectionIds provided. Please specify at least one.",
            },
          ],
        };
      }

      const script = builder.build();

      return {
        content: [
          {
            type: "text" as const,
            text: `Save the following as a .scr file and run in Fusion 360 Electronics via Automate > Script:\n\n\`\`\`\n${script}\n\`\`\``,
          },
        ],
      };
    }
  );
}

/**
 * Place design BOM parts on the schematic in grouped columns.
 * Returns the updated Y position after placement.
 */
function placeDesignParts(
  builder: ScrBuilder,
  parts: DesignPart[],
  originX: number,
  startY: number,
  cols: number,
  colSpacing: number,
  rowSpacing: number
): number {
  const groups = groupParts(parts);
  let currentY = startY;

  for (const group of groups) {
    builder.addComment(`── ${group.groupName} (${group.parts.length}) ──`);

    // Sort parts within group by reference designator naturally
    group.parts.sort((a, b) => {
      const aPrefix = a.ref.replace(/[0-9]+$/, "");
      const bPrefix = b.ref.replace(/[0-9]+$/, "");
      if (aPrefix !== bPrefix) return aPrefix.localeCompare(bPrefix);
      const aNum = parseInt(a.ref.replace(/^[A-Za-z]+/, ""), 10) || 0;
      const bNum = parseInt(b.ref.replace(/^[A-Za-z]+/, ""), 10) || 0;
      return aNum - bNum;
    });

    for (let i = 0; i < group.parts.length; i++) {
      const part = group.parts[i];
      const col = i % cols;
      const row = Math.floor(i / cols);
      const x = originX + col * colSpacing;
      const y = currentY - row * rowSpacing;

      builder.addComponent(part.deviceset, part.ref, x, y);

      // Set value if it differs from the deviceset name
      if (part.value && part.value !== part.deviceset) {
        builder.setValue(part.ref, part.value);
      }
    }

    // Move Y down past this group's rows, plus a gap between groups
    const rowsInGroup = Math.ceil(group.parts.length / cols);
    currentY -= rowsInGroup * rowSpacing + 100;
    builder.addComment("");
  }

  return currentY;
}
